### ISSUE TITLE
Fire TV - Not smooth video if frame matching enabled.

### ISSUE THREAD

**Issue by nicosea** [CastagnaIT/plugin.video.netflix#197] opened 2019-09-09 08:33 UTC
#### Your Environment
- Netflix add-on version: 15.2 
- Operating system version/name: Fire OS 6.3.1.2
- Device model:  Fire TV Stick 4K

Used Operating system:
* [x ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When I enable match framing in Kodi player option, I am able to automatically switch the TV frequency to 24 fps when a Netflix movie or series is originally encoded in 24fps, but video is not smooth, it is like some frame are dropped and some duplicated. 
I tested the Netflix plugin-in also on raspberry and windows, on these system it works perfectly. 

#### Expected behavior

When Fire stick TV 4K switch to 24fps automatically, 24 fps netflix videos should be extremely smooth at played at native fps.

#### Actual behavior

24 fps videos are not played smooth, even though fire stick kodi set TV on 24fps. The funny thing is that if I try to change a video or audio settings while I am watching the movie and part of kodi gui appears on top of the movie to show player options, than the movie plays wonderfully smooth for all the time the gui is on. If I do nothing and I go back to "full screen" than video starts chopping again.

#### Steps to reproduce the behavior

1. 
2. 
3. 

### Debug log

The debug log can be found here: 

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by rwijnhov** [comment] 2019-09-09 10:32
I am seeing the exact same thing on my firestick 4k.

**Comment by nicosea** [comment] 2019-09-09 16:46
Is mindhunders available at 24fps? I have this issue only with Netflix videos with 24fps.
So strange that videos become smooth as soon as and as long as the kodi GUI appears when you want for example pause the video or access the player settings to choose for example a different audio language.

**Comment by Smeulf** [comment] 2019-09-09 17:19
If I'm correct, this is handeled by InputStream. @peak3d I am right?

**Comment by peak3d** [comment] 2019-09-09 17:34
It's kodi kernel, frame timing is handled using Android Choreographer. There is not much room for further improvements.

**Comment by rwijnhov** [comment] 2019-09-09 17:38
The first pic is the info on the juddering 1080p London has fallen. Second picture is on 4k hdr mindhunters with no stuttering or judder whatsoever? Is this isue firestick related or on 
All android boxes?
![IMG_20190909_193145434](https://user-images.githubusercontent.com/29757781/64553097-0ca13980-d339-11e9-91bd-fa3afb948370.jpg)
![IMG_20190909_193259772](https://user-images.githubusercontent.com/29757781/64553107-11fe8400-d339-11e9-9e0d-742d0997546d.jpg)

**Comment by nicosea** [comment] 2019-09-09 17:43
I noticed that Mindhunter is encoded in h265, while London has fallen in h264, but not sure if this could be a reason (maybe h265 is better handled by fire stick because hardware acceleration is supported?)

**Comment by Smeulf** [comment] 2019-09-09 17:58
Regarding @peak3d answer, it a Kodi/Android bug, so unfortunately nothing we can do.

**Comment by rwijnhov** [comment] 2019-09-09 18:05
Ok just tested h265 Netflix plays great h264 Netflix stutters. So this is a Kodi android bug? Or a firestick 4k bug? If yes only solution for 264 hdr Atmos is appletv?

**Comment by peak3d** [comment] 2019-09-09 18:29
It is most likely a driver bug / feature. for example if decoder does not provide proper PTS values, or has tunneld playback mode fixed. From my investigation palyback is much better if you play this on 59,94 TV refreh rate

**Comment by nicosea** [comment] 2019-09-10 11:17
Is there anything we could mention to KODI team to fix it in the next Android Kodi release?

**Comment by CastagnaIT** [comment] 2019-09-14 12:03
I'm sorry but i have to close this PR it is not related to the addon,
for this problem you have to request assistance in Kodi forum

**Closed by CastagnaIT** 2019-09-14 12:03 UTC

**Comment by Uukrull** [comment] 2019-10-13 16:52
> So strange that videos become smooth as soon as and as long as the kodi GUI appears

@nicosea: that gave me an idea because it also happens with playerdebuginfo enabled (ctrl+shift+o), so I modified the source code to always display playerdebug info but with an empty string.

Comment out these lines:
https://github.com/xbmc/xbmc/blob/53484b6a92f63df6d4faa46d0b5f38e15327cb3d/xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp#L725
and
https://github.com/xbmc/xbmc/blob/53484b6a92f63df6d4faa46d0b5f38e15327cb3d/xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp#L742

It's a nasty hack but it works :)
The problem can be easily checked with the first episode of Cannon Busters where at the start there is a panning that is very choppy on the Fire TV 4K.

**Comment by nicosea** [comment] 2019-10-14 18:14
> > So strange that videos become smooth as soon as and as long as the kodi GUI appears
> 
> @nicosea: that gave me an idea because it also happens with playerdebuginfo enabled (ctrl+shift+o), so I modified the source code to always display playerdebug info but with an empty string...

Do you mean like below?
// if (m_renderDebug)
// m_debugRenderer.SetInfo(audio, video, player, vsync);

How can I edit this file directly on FireTV?
Or should I upload an edited RenderManager.cpp via FTP or SSH?

**Comment by Uukrull** [comment] 2019-10-14 18:52
You have to compile the source code.

**Comment by mano3m** [comment] 2020-07-05 20:34
I can confirm using an overlay like CTRL+SHIFT+O completely fixes the stutters with 1080p streams on my fire TV 4k. What does Kod do differently with an overlay on screen?
