### ISSUE TITLE
Don't add to library TV Shows

### ISSUE THREAD

**Issue by DanilosTeam** [CastagnaIT/plugin.video.netflix#104] opened 2019-06-10 15:41 UTC
Has an error when add ever tvshow to library.

I use last plugin version installed from your repo. The system is the last libreelec con Pi3.

Screenshot: 
https://i.ibb.co/kQC5Q6V/IMG-20190610-170254.jpg

Log:
http://ix.io/1Lp8

Thx!!!

**Comment by DanilosTeam** [comment] 2019-06-10 15:43
Config log: http://ix.lo/1Lpf

**Comment by Smeulf** [comment] 2019-06-10 16:00
Hi, this is a known issue in 0.14.4

The last version from the master branch fixes it. You can download it as zip and install it manually to solve your issue, or revert to 0.14.3

**Comment by DanilosTeam** [comment] 2019-06-10 16:29
I have 0.14.3.

**Comment by Smeulf** [comment] 2019-06-10 16:36
So please try last master. 

We're working to improve the library, and to be honest I can't remember the particular case this error appears, but I'm certain we fixed it.

**Comment by DanilosTeam** [comment] 2019-06-11 13:36
Solved with v0.14.3

Repo version v0.14.4 is a little disaster :-)

Thanks for help!

**Comment by Smeulf** [comment] 2019-06-11 13:45
The fautive commit was ment to solve an issue while exporting a season. But it had side effects on other parts (tv show or movies) we didn't see in time. As said, it's fixed for next release. 

We're just a few people working on this add-on, and not full time. So glitches may happen...

**Comment by DanilosTeam** [comment] 2019-06-11 19:02
The problem is that the repository installs a version with many bugs (.4) 

The (.3) version works really well. 

Thanks for your work.

**Comment by Smeulf** [comment] 2019-06-11 21:40
Yeah, but it's still a 0.x version ^^

0.14.3 contains bugs too, some fixed in 0.14.4, but indeed for you, it's not usable.

Anyway, we'll make it as perfect as possible with time!

Cheers!

**Comment by zosky** [comment] 2019-06-12 17:51
confirmed downgrading to .3 resolves. 

i too installed .4 (f/repo) - exporting *each season* works, exporting *the entire show fails* 

thank you for the *workaround* & for continuing to push this thing forward.

**Comment by Smeulf** [comment] 2019-06-19 23:50
Should be fixed for both show and season in 0.14.5.

Btw @zosky, I'm considering to remove seasons and episodes export in the future, as it's incompatible with 'export new episodes' as I entend to do it. 

Is there a specific reason you exported only seasons or was it for a test?

**Comment by dm2912** [comment] 2019-06-22 15:55
word of warning, since yesterday if i export anything to my library im getting a http error and then im getting locked out of netflix both within the add-on and website.. 

takes anything from 2 to 48 hours for the lock to clear :/

**Comment by CastagnaIT** [comment] 2019-06-22 16:05
yes if you export or sync too many things you are banned from netflix,
normal behaviour, you can reduce the number of exports to single season

**Comment by dm2912** [comment] 2019-06-23 18:26
yeh, ive been unlocked today. looked back and it looks like adding shameless which is about 8 seasons of 24 episodes was what did it.

will get in the habit of only adding the season i am watching to the library

**Comment by CastagnaIT** [comment] 2019-06-23 18:29
can you tell me which show tv?

**Comment by dm2912** [comment] 2019-06-23 18:39
> can you tell me which show tv?

the last one scanned before i was locked out was shameless - 9 seasons, 110 episodes.. so yeah, i guess that was pushing it :D ive added single seasons without problem. 

https://en.wikipedia.org/wiki/Shameless_(American_TV_series)

**Comment by CastagnaIT** [comment] 2019-06-23 18:41
thanks this information can help me to find a solution or limit

**Comment by Smeulf** [comment] 2019-06-23 19:46
@dm2912 'last ine scanned' you said.

Does that mean you exported many before get locked?

**Closed** 2019-07-02 18:55 UTC
