### ISSUE TITLE
MSLerror - This title is not available to watch instantly

### ISSUE THREAD

**Issue by guy99au** [CastagnaIT/plugin.video.netflix#1278] opened 2021-12-11 07:07 UTC
#### Your Environment
- Netflix 1.18.1
- Operating system version/name: Android 9.0 & Android 10
- Device model:  Nvidia Shield & Mecool KM1

Used Operating system:
* [x ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Videos will not play, return error: MSLerror. This title is not available to watch instantly. 

The debug log can be found here:
~https://pastebin.com/TZJH8Mf7~ **redacted -> wrong link or deleted**

#### Other information
Tried logging out, then in again, restarting TV box, checked ESN (both OK) and changed Expert setting to L3 - nothing worked. The fact this has only happened today on two different boxes suggests a change at Netflix or maybe inputstream.adaptive?

**Comment by Tony763** [comment] 2021-12-11 07:49
Same on my side, I run kodi on Ubuntu 21.10 and a same error occurred.

[log](https://pastebin.com/cv2zRLiH)

**Comment by CastagnaIT** [comment] 2021-12-11 10:22
as explained in wiki the main cause (or more causes) of this error currently still to be unknown
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#This-title-is-not-available-to-watch-instantly

> suggests a change at Netflix or maybe inputstream.adaptive?

is this a random theory of yours or a kind of suggestion to change something in specifics?
I have already tried to solve the problem but have not been able to understand the cause,
if you have some solution to propose, i am open to listening for solutions to improve the situation,
otherwise this issue will be closed in next days, there are no solutions from my part

**Comment by CastagnaIT** [comment] 2021-12-11 10:51
these are some some info collected over the time, if can help:

https://github.com/CastagnaIT/plugin.video.netflix/wiki/Dev.-unresolved-issues#license-request-error-this-title-is-not-available-to-watch-instantly

**Comment by fedevx** [comment] 2021-12-11 11:02
I don't have the "Force L3" in my raspberry pi 4, Kodi installation (Linux).

Under "Widevine - Force security level" it says "Disabled" in red color. Is there a way to change this?

**Comment by fedevx** [comment] 2021-12-11 11:36
While @guy99au might have made a guess, I must say that it would be a very strange coincidence if all of us started getting the same error today out of the blue. I'd be inclined to believe something must have changed as well.

Is there a difference between the logs you have seen for this error before and those seen today @CastagnaIT ?

**Comment by Tony763** [comment] 2021-12-11 11:37
I can't play no movie. Even those which runed just fine last week.

**Comment by fedevx** [comment] 2021-12-11 11:55
Would this be where it fails?

```
2021-12-11 08:30:32.182 T:32405   ERROR <general>: CCurlFile::Open failed with code 0 for http://127.0.0.1:46809/msl/get_license?videoid=80192815:
 
2021-12-11 08:30:32.182 T:32405   ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
2021-12-11 08:30:32.182 T:32405   ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
```

Based on the logs from @Tony763

**Comment by CastagnaIT** [comment] 2021-12-11 12:15
@fedevx  `inputstream.adaptive` is no importance in this case, is the netflix license request that fails, and failure does not necessarily presume a problem our side, it would not be the first time that netflix could have temporary service failures which are automatically resolved

only android could have L1 all other devices are always L3, then you cannot force L3 because you are already L3
as said there are no known reason why this error happen and also can disappears automatically

your posted log is inacessible then i have no idea if it is really the same issue of @Tony763,
comparing @Tony763 log with a my old log in my archive the only difference is:
`bladeRunnerCode`  3078
`code` DEVICE_EOL_FINAL

where in the past was:
`bladeRunnerCode` 1044
`code` FAIL

this could means a lot of thing and nothing... example
could be that this error cover new different thing from the past
or is only a refactor of the old code number
or also is totally different error
i have no idea

recently i have check the license request and i have not found new changes
I'll do a test on linux coreelec later, but from my Windows machines to me works good as usual

**Comment by wagnerch** [comment] 2021-12-11 12:28
Same issue here, South East US.
- CE 19 not working
- LE 10 not working
- Windows via Firefox is fine
- Raspberry Pi OS Bullseye via Chromium is fine

Tried logout & login.  Tried via settings to reduce to 576p, no change.  Same sha1 for libwidevinecdm.so on Raspberry Pi OS, LE, & CE.  So I am guessing it is ARM-centric, whatever it is.

**Comment by Liqianyu** [comment] 2021-12-11 12:30
It happens on Kodi 19 (different package name) & Kodi 20 at the same time. On yesterday I was able to play it normally. It's definitely not a coincidence that there is some kind of cause for the problem. Reinstalling ISA and re-logging into Netflix did not help. (at least for me)

**Comment by CastagnaIT** [comment] 2021-12-11 12:58
i have now tried on my ARM amlogic CoreElec 20 (not updated old nightly) but works without errors
it has also request to update widevine to 2.10.2252.5 (and after that i have rebooted the device before run the videos)

>  Is this some sort of A/B testing or account based?

could be, and if this is a new change could also be applied in specified countries only before a worldwide rollout,
this therefore prevents any testing on my part, at least for now...

**Comment by CastagnaIT** [comment] 2021-12-11 14:27
maybe trying to update the useragent could solve, who wants try to update and give a feedback:
[plugin.video.netflix_1.18.1+matrix.1_20211211_ua.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7697195/plugin.video.netflix_1.18.1%2Bmatrix.1_20211211_ua.zip)

**Comment by Liqianyu** [comment] 2021-12-11 14:27
I tested using Kodi 18.9 + Netflix Add-On v.1.12.8-Leia +NFAuthenticationKey Login with Shield TV Pro 2017. Guess what? Normal playback!
Then I went back to Shield TV Pro 2019 and Kodi 19 & 20 still didn't work. But . . Kodi 18.9 played just as well!
This seems to prove that there is no relationship with the account, device (ESN).

@CastagnaIT 
Does this mean that the problem is likely to be with inputstream adaptive 19 & 20 ?

**Comment by Liqianyu** [comment] 2021-12-11 14:37
@CastagnaIT
Unfortunately, after testing plugin.video.netflix_1.18.1+matrix.1_20211211_ua.zip doesn't seem to help fix the issue.
Which is the closest Matrix version to v.1.12.8-Leia? I think I can port v.1.12.8 to Matrix to test it.

**Comment by wagnerch** [comment] 2021-12-11 14:51
@CastagnaIT I tried this UA below earlier and it didn't make a difference.  Looking at the cadmium player, it appears the manifest request has a few new parameters:

                                    manifestVersion: A.sh.lVa ? "v2" : "v1",
                                    desiredSegmentVmaf: A.config().lbb ? A.config().gUa : A.config().hUa,
                                    requestSegmentVmaf: A.config().GVb,
                                    supportsPartialHydration: A.sh.xM,
                                    contentPlaygraph: A.sh.QSa

Tried to throw in a hardcoded manifestVersion: v1, but no change on that.  desiredSegmentVmaf seems to be the same as desiredVmaf.


```
+    chrome_version = 'Chrome/95.0.4638.78'
...
+        return base.replace('%PL%', '(X11; CrOS armv7l 13597.84.0)')
```

**Comment by CastagnaIT** [comment] 2021-12-11 14:58
@Liqianyu the only difference between the addon for Kodi 18 and 19/20, is that on 19/20 we use the new manifest request version
the 18 still use the deprecated manifest request that with some systems not allow full hd, and is probabile that on Kodi 18 i have not backport some patches that i not remember, that version is not more mantained...
from my POV is not a good way to make tests from kodi 18, we have to use the current manifest request version not the deprecated one
@wagnerch said that with kodi not works, but with browser works, this could suggest some changes on website that need to be investigated

@wagnerch is possible that that some parameters are changes but to check you have to add a break point in browser debugger
and copy the manifest data, but need to be recheck also the license request,
or install the mitm proxy (my repo) get the fuill log of website msl dialogs (better way)

**Comment by wagnerch** [comment] 2021-12-11 15:03
@CastagnaIT Yeah, that's what I was thinking as well.  I'll see about setting up the mitm proxy again and run it from Chromium on Raspberry Pi OS.

**Comment by dgarciam** [comment] 2021-12-11 15:20
I got this same error. CE on Odroid N2 running nightly updates.
I don't know if this is of help or not. I went to `~/.kodi/temp` and did a  `cat kodi.log |grep netflix`
I got the following results:

`CoreELEC:~/.kodi/temp # cat kodi.log |grep netflix
2021-12-11 00:09:37.239 T:4815     INFO <general>: CAddonMgr::FindAddons: plugin.video.netflix v1.18.1+matrix.1 installed
2021-12-11 00:09:44.147 T:4898     INFO <general>: [plugin.video.netflix (0)] The debug logging is set as DISABLED
2021-12-11 00:09:59.579 T:5066     INFO <general>: [plugin.video.netflix (1)] The debug logging is set as DISABLED
2021-12-11 00:10:00.293 T:5066     INFO <general>: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-12-11 00:10:02.632 T:5073     INFO <general>: [plugin.video.netflix (2)] The debug logging is set as DISABLED
2021-12-11 00:10:06.094 T:5073     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-12-11 00:10:10.404 T:5073     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-12-11 00:10:12.119 T:5073     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-12-11 00:10:15.665 T:5073     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-12-11 00:10:18.756 T:5073     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-12-11 00:10:20.641 T:5073     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-12-11 00:10:20.678 T:4815     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/80189685/season/80189598/episode/80244464/?profile_guid=RZJTBM44O5BXJEYW5T25L273TA
2021-12-11 00:10:22.039 T:5103    ERROR <general>: [plugin.video.netflix (0)] Full MSL error information:
2021-12-11 00:10:22.039 T:5103    ERROR <general>: [plugin.video.netflix (0)] {"id": 16391994218395, "version": 2, "serverTime": 1639199421973, "error": {"code": "FAIL", "detail": "licensedManifest/playapi-PLAY_API_ERROR: PBO_UNEXPECTED_EXCEPTION [viewableId=[80244464]]", "display": "This title is not available to watch instantly. Please try another title.", "alert": null, "alertTag": "", "errorActionId": 3, "errorExternalCode": 0, "errorNccpCode": 0, "errorReasonCode": 0, "errorSubCode": 0, "errorDisplayMessage": "This title is not available to watch instantly. Please try another title.", "nccpError": {}, "bladeRunnerMessage": "licensedManifest/playapi-PLAY_API_ERROR: PBO_UNEXPECTED_EXCEPTION [viewableId=[80244464]]", "bladeRunnerCode": "PLAY_API_ERROR", "pboc": true}, "from": "playapi"}
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 36, in do_GET
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 99, in handle_msl_request
                                                       manifest_data = server.server.netflix_session.msl_handler.get_manifest(videoid, unquote(challenge), sid)
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_utils.py", line 55, in error_catching_wrapper
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_handler.py", line 95, in get_manifest
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_handler.py", line 196, in _get_manifest
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_requests.py", line 165, in chunked_request
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_requests.py", line 220, in _process_chunked_response
2021-12-11 00:10:39.565 T:5103    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_requests.py", line 249, in _raise_if_error
2021-12-11 00:10:39.571 T:5101    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80189685/season/80189598/episode/80244464/?profile_guid=RZJTBM44O5BXJEYW5T25L273TA]
`

I should note that this happened right after an update on both the plugging and the nightly update. 

If you need specific info, i'll be glad to pass it along

**Comment by quietvoid** [comment] 2021-12-11 15:30
I did mention on the forums that I'm getting an MSL error only when HDR is enabled on my Firestick 4K Max.

If I disable HDR  (device, not addon or Kodi) the addon can still play 2160p correctly.
Using Kodi 20 Nexus.

I can provide some logs of both in a couple hours

**Comment by CastagnaIT** [comment] 2021-12-11 15:34
to all, if you want add logs that you think that report different data from the log posted on first comment of this thread,
please do not attach the log as text, instead attach the weblink by using service like https://paste.kodi.tv/
and you have to be sure to have the kodi debug and addon debug enabled

**Comment by wagnerch** [comment] 2021-12-11 15:42
@CastagnaIT Sent a proxy log, logging in, selecting a video "Small Crimes" and playing a few seconds, on Pi 4.  Sent to your Paypal e-mail address.

**Comment by CastagnaIT** [comment] 2021-12-11 15:49
@wagnerch  found thanks! I try to see

**Comment by pfrieske** [comment] 2021-12-11 16:15
same here - Android 10 arm64, Kodi 19.3, won't play anything as of circa 12 hours ago, no problems before.

Thanks and looking forward to solution!

**Comment by wagnerch** [comment] 2021-12-11 16:18
@CastagnaIT This is what I get in my debug log:

https://paste.kodi.tv/idixukidog.kodi

```2021-12-11 11:15:10.786 T:2561    ERROR <general>: [plugin.video.netflix (0)] {"id": 16392393106219, "version": 2, "serverTime": 1639239310750, "error": {"code": "FAIL", "detail": "licensedManifest/playapi-PLAY_API_ERROR: PBO_UNEXPECTED_EXCEPTION [viewableId=[80164212]]", "display": "This title is not available to watch instantly. Please try another title.", "alert": null, "alertTag": "", "errorActionId": 3, "errorExternalCode": 0, "errorNccpCode": 0, "errorReasonCode": 0, "errorSubCode": 0, "errorDisplayMessage": "This title is not available to watch instantly. Please try another title.", "nccpError": {}, "bladeRunnerMessage": "licensedManifest/playapi-PLAY_API_ERROR: PBO_UNEXPECTED_EXCEPTION [viewableId=[80164212]]", "bladeRunnerCode": "PLAY_API_ERROR", "pboc": true}, "from": "playapi"}
```

**Comment by CastagnaIT** [comment] 2021-12-11 16:30
@wagnerch not found changes in license request but manifest only as you mentioned
and in your log i can see that is stuck in manifest request

i have adapted the changes: [plugin.video.netflix_1.18.1+matrix.1_20211211_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7697359/plugin.video.netflix_1.18.1%2Bmatrix.1_20211211_t1.zip)

**Comment by wagnerch** [comment] 2021-12-11 16:41
@CastagnaIT Yep, appears to work with this update.

**Comment by quietvoid** [comment] 2021-12-11 16:42
> i have adapted the changes: [plugin.video.netflix_1.18.1+matrix.1_20211211_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7697359/plugin.video.netflix_1.18.1%2Bmatrix.1_20211211_t1.zip)

This is working for me too.

**Comment by CastagnaIT** [comment] 2021-12-11 16:43
we are lucky we surpassed speed records in solving a problem :)
i will prepare the next release

**Comment by pfrieske** [comment] 2021-12-12 00:29
> @wagnerch not found changes in license request but manifest only as you mentioned and in your log i can see that is stuck in manifest request
> 
> i have adapted the changes: [plugin.video.netflix_1.18.1+matrix.1_20211211_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7697359/plugin.video.netflix_1.18.1%2Bmatrix.1_20211211_t1.zip)

Hi, thanks for the great plugin!

I've downloaded above version but Kodi (19.3) gives error when trying to install 'failed to install add-on from zip file' - any ideas?

Could file name  matter? (Random name after saving the download)?

Thanks!

**Comment by YourTheFinestIveEverKnown** [comment] 2021-12-12 01:19
Confirmed, this fixed it for me also. Great Plugin! Thanks.

**Comment by Liqianyu** [comment] 2021-12-12 05:34
@pfrieske 
This is a test version, which I think requires kodi nightly builds.

**Comment by pfrieske** [comment] 2021-12-12 06:09
Thank you!

**Comment by ziporah** [comment] 2021-12-12 19:43
I tried updating to this version, using libreelec 10.0, with Matrix v19.1, updated the plugin to latest version, but I'm still receiving the same error as above. I verified the patch is in place, by searching the patched files for the code changes and they are in place. Can I provide any more info to assist on debugging the issue?

**Comment by guy99au** [comment] 2021-12-13 06:24
Many thanks for your hard work. Working well.

**Comment by CastagnaIT** [comment] 2021-12-13 07:24
@ziporah you have to provide the full kodi debug log by following the instructions in readme

**Comment by ziporah** [comment] 2021-12-14 17:29
@CastagnaIT didn't have time yesterday to get the debug log. Meanwhile problem is solved. For those who still have problems: in Expert settings:
* Clear in-memory cache and on-disk cache
I hit this button while I was in the expert menu and was getting the debug log. Magically everything started working again!

**Comment by grandchamp** [comment] 2021-12-17 22:40
Got the issue today and the version posted here made it work again. Thanks @CastagnaIT

**Closed** 2021-12-18 08:44 UTC
Labels: Triage: Confirmed, Resolution: Fixed

**Comment by Artiom-M** [comment] 2022-02-01 11:03
I've got the same issue with v.1.12.8-Leia. Any chance to backport the fix?

**Comment by mcdnsd** [comment] 2022-02-03 23:02
I also have the same issue on a RP4.arm / LibreELEC 9.2.8 (Leia) / Netflix v1.12.8. I have tested LibreELEC 10,0 with this fix and can confirm this issue is resolved there, but the Raspberry Pi 4B+ has other issues with LibreELEC 10 that means I am unable to upgrade permanently at this time. I would be very grateful if this fix could be added to Leia also. Thanks

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7998852/kodi.log)
,

**Comment by AreaScout** [comment] 2022-02-05 08:56
Yes, please backport to Leia 👍

**Comment by VGerris** [comment] 2022-02-05 20:41
I can't find the L3 setting but had this issue today. Reinstalled widevine in plugin, and rebooted. Then I saw a notification of other updates inlcuding Netflix. Did work after another reboot
