### ISSUE TITLE
Email or password is incorrect

### ISSUE THREAD

**Issue by guicel** [CastagnaIT/plugin.video.netflix#67] opened 2019-04-29 19:55 UTC
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used
DailyBuild 0.14.0_20190422

### Description
Hello,
I installed the addon correctly. Enter my email and my password.
I can connect to my accounts and my lists when I want to start a video I have the error message "email or password is incorrect" and the video does not start.

Thank you for your help and all the work you have done.

## Context (Environment)
I use a raspi 3 B+ with Librelec 9.01
### Installation

* [X ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
libreelec 9.01
## Debug log
https://pastebin.com/raw/j5nct92v
## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by guicel** [comment] 2019-04-29 20:09
Hi,
for information my location is France
Thanks a lot

**Comment by CastagnaIT** [comment] 2019-04-30 17:48
i need the full log with kodi debug infos enabled, no cutted log..

**Comment by guicel** [comment] 2019-04-30 20:57
I'm sorry,
i hope this is better  http://ix.io/1HGG
Thanks a lot

**Comment by CastagnaIT** [comment] 2019-05-01 09:30
unfortunately not here there is no debugging information, you have not activated the kodi debug logging

**Comment by guicel** [comment] 2019-05-01 10:35
Sorry, I thought I did it. I'll tick all the boxes and start again.

**Comment by guicel** [comment] 2019-05-01 10:43
I hope this is better http://ix.io/1HJh

or  http://ix.io/1HJi

I actived all the option in the system menu of Kodi. 
There are 2 paste logs button.
Thanks a lot

**Comment by guicel** [comment] 2019-05-01 16:12
This paste might be better (only this day and color...):
https://paste.kodi.tv/keyurezuyu.kodi

**Comment by CastagnaIT** [comment] 2019-05-01 16:13
from what i can see i don't find much explanation for your problem,
decoding the error data clearly says email or password incorrect

`{"internalcode":205007,"messageid":15809443405631,"errorcode":7,"errormsg":"Email or password is incorrect.","timestamp":1556707151}`

feedback from other users who have had a similar problem,
have solved by changing passwords from netflix, probably netflix for some reason blocked access

other alternative it is possible that the videos you are trying to see need to have enabled the profile VP9 or else HEVC (do not enable both), you can try enable/disable the profiles in the expert settings of addon

**Comment by Smeulf** [comment] 2019-05-01 18:23
Dumb question : could your password contains a very special char, like a space maybe ?

I remember some software that couldn't handle such case...

(Please do not disclose your full password!)

**Comment by guicel** [comment] 2019-05-01 19:31
I have tested VP9 or HEVC but aren't solution.
My email and my pass not contains special char. just upper case and number

**Comment by guicel** [comment] 2019-05-01 20:20
What surprises me is that I add to the list of videos and my favorites netflix so my password at this time did not pose a problem.

**Comment by spectroman** [comment] 2019-05-02 19:50
Same here. Works to login, logout, browse lists, anything... when select something to play, same error... tested account in other place it works everywhere else. So account is not blocked, login is valid and so on... using OSMC.

**Comment by Smeulf** [comment] 2019-05-02 20:54
Sounds like you're not allowed to access the stream itself then.

Would it be possible you're having a 'basic' Netflix account (lowest coast) and trying to access HD streams ?

**Comment by guicel** [comment] 2019-05-03 06:15
I haven't a 'basic' Netflix account.
I looked at the options I did not see anything that could be a problem.

**Comment by CastagnaIT** [comment] 2019-05-03 18:01
can you do this test?
go to the netflix via web browser,
change the language of the profile used to English,
then try play with kodi

**Comment by spectroman** [comment] 2019-05-03 18:09
That's exactly how I can figure that its not a stream or an account problem... I got a "blank" browser and configured the widevinecdn, connected to netflix with the same account, login, logout, login again, streamed things that won't work on the Kodi / OSMC.

So the user is set to English and I have other profiles in different languages (EN and NL here) all of them behaves exactly in the same way, works everywhere else, but not on the Kodi.

I tested on a set-top box (IPTV kinda thing), chrome browser, mobile, on different computers, multiple login at the same time... it all works fine, but not the Kodi plugin.

**Comment by CastagnaIT** [comment] 2019-05-03 18:26
as soon as I find time, i'll do a test on librelec 9 too
the last time i installed librelec 9 did not want to know to create a bootable partition... bah...

**Comment by guicel** [comment] 2019-05-03 20:05
I have change the language but there is no change.
Sorry

**Comment by Smeulf** [comment] 2019-05-03 20:58
@guicel can you try to rename Userdata/addon_data/plugin.video.netflix/settings.xml to settings.xml.bak, reboot your Pi, and configure the addon again ?

Just set your email and password, and ensure HEVC and VP9 profiles are disabled.

If you still have an error, a new log might be interesting.

Btw, I assume you don't use any VPN to access Netflix right ? If you use one, please try without.

**Comment by guicel** [comment] 2019-05-04 12:32
i have rename Userdata/addon_data/plugin.video.netflix/settings.xml to settings.xml.bak
I have configure the addon with my mail and pass without HEVC and VP9.
Appears the message: "Login successful"
I initially leave the ESN automatic and I had the same error.
I put the ESN from my netflix android app (NFANDROID1-PVR-.....)
But I also have the same error.
Here is the log during the last test
https://paste.kodi.tv/apometimok.kodi

I don't use vpn.
There is a week i try with a vpn (with US location) but same error

**Comment by CastagnaIT** [comment] 2019-05-04 15:45
I just installed Librelec 9.01, on my old pc and netflix works perfectly,
you can always try to do a wipe and reinstall librelec

**Comment by spectroman** [comment] 2019-05-04 18:41
yeah,,, no.. 

```2019-05-04 18:35:57.570 T:1579144048   ERROR: GetDirectory - Error getting
2019-05-04 18:36:27.071 T:1936929440   ERROR: Previous line repeats 6 times.
2019-05-04 18:36:27.071 T:1936929440  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/80190843/season/80190926/episode/80190581/
2019-05-04 18:36:27.072 T:1442308976  NOTICE: Creating InputStream
2019-05-04 18:36:27.208 T:1442308976   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2019-05-04 18:36:27.903 T:1512825712   ERROR: [plugin.video.netflix (0)] Full MSL error information:
2019-05-04 18:36:27.904 T:1512825712   ERROR: [plugin.video.netflix (0)] {"entityauthdata": {"authdata": {"pubkeyid": "MSL_TRUSTED_NETWORK_SERVER_KEY", "identity": "Netflix"}, "scheme": "RSA"}, "errordata": "eyJpbnRlcm5hbGNvZGUiOjIwNTAwNywibWVzc2FnZWlkIjoxMTY0MDkyOTU2MTI0NzEwLCJlcnJvcmNvZGUiOjcsImVycm9ybXNnIjoiRW1haWwgb3IgcGFzc3dvcmQgaXMgaW5jb3JyZWN0LiIsInRpbWVzdGFtcCI6MTU1Njk5NDk4N30=", "signature": "J3+QKxeNlexNnS21Is7GJkLc2zAL2CBRsqB+hfA0KmAhT21jQIzEwIcs2jW61h8N4FnRxD/oItNAs2FPGfviuxnt4WQS9R6pvcHJU5ZbtgLbsLLj996Ya5YQSUi+s3o4G7QF3PHanrRNd6imfpnpgxX28KQPzVYnZs8ei75n7qGLYGeRGnnPdidcRTA5vwGMBKtUwCSb+XU0K99aLXe6qXod5yKTN7+XWzZXIDc/bvlppJD+ngUDIwBprQpqmi3d6e4JsT2jnps3G5PlhyHOpH/bIc+cCJ1UcC9+pGGIGc5GhTd22enuN+5qb3iTQPdrwN1cHzYTXl0u5H/VqqDYxw=="}
2019-05-04 18:36:35.843 T:1512825712   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 47, in do_GET
                                                data = self.server.msl_handler.load_manifest(int(params['id'][0]))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 41, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 237, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 109, in load_manifest
                                                manifest = self._load_manifest(viewable_id, g.get_esn())
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 237, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 195, in _load_manifest
                                                manifest_request_data, esn)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 237, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 246, in _chunked_request
                                                self.request_builder.msl_request(request_data, esn)))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 237, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 267, in _process_chunked_response
                                                return _raise_if_error(response.json())
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 291, in _raise_if_error
                                                raise MSLError(_get_error_details(decoded_response))
                                            MSLError: Email or password is incorrect.
2019-05-04 18:36:35.845 T:1442308976   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 500
2019-05-04 18:36:35.845 T:1442308976   ERROR: CCurlFile::Open failed with code 500 for http://localhost:35683/manifest?id=80190581:
2019-05-04 18:36:35.845 T:1442308976   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:35683/manifest?id=80190581
2019-05-04 18:36:35.846 T:1442308976   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:35683/manifest?id=80190581)
2019-05-04 18:36:35.846 T:1512825712   ERROR: Traceback (most recent call last):
2019-05-04 18:36:35.847 T:1512825712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2019-05-04 18:36:35.847 T:1512825712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2019-05-04 18:36:35.847 T:1512825712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-05-04 18:36:35.848 T:1512825712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
2019-05-04 18:36:35.848 T:1512825712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
2019-05-04 18:36:35.848 T:1512825712   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2019-05-04 18:36:35.848 T:1442308976   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80190843/season/80190926/episode/80190581/]
2019-05-04 18:36:35.849 T:1512825712   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2019-05-04 18:36:35.849 T:1442308976  NOTICE: CVideoPlayer::OnExit()
2019-05-04 18:36:35.849 T:1512825712   ERROR: error: [Errno 32] Broken pipe
2019-05-04 18:36:35.956 T:1936929440  NOTICE: CVideoPlayer::CloseFile()
```

On LibreELEC 9.01, using the latest Daily build. 

Exactly the same behavior, can login, logout, show everything correctly, but when is going to play, I got the same error. So no OSMC and no LibreELEC.. :(

**Comment by Smeulf** [comment] 2019-05-04 22:00
I use a Pi3 and a Pi2 under LibreELEC 9.0.1 both with Netflix, and I don't have such problem...

**Comment by guicel** [comment] 2019-05-05 08:15
Smeulf, have you change ESN in Addon ?

**Comment by Smeulf** [comment] 2019-05-05 08:41
No I haven't change the ESN, but I remember I installed asciidisco's addon first, then upgrade to this version.

I'll try to set up a fresh LE9.0.1 with addon on a different SD card in the evening and set up Netflix again, just to see if I can reproduce the issue or not.

I'll report ASAP.

**Comment by guicel** [comment] 2019-05-05 13:12
I have reinstall librelec9.01.
i have to install asciidisco's addon to try.
it did not work because inputstream was not installed but as it did not tell me I updated with the latest daily version of this repository. Afterall installation same error ....
But I was in the libreelec menu and I reset all the settings.
I reinstall inputstream and the daily addon directly. I put my email and my pass without changing the ESN.
It works.
I have to test by reinstalling the rest ...

**Comment by Smeulf** [comment] 2019-05-05 18:40
@guicel nice to see you found a way to make it work!

On my side, I can't find a working micro sd card, so my test is on standby.
I'll run it starting May 13th, 'cause I'll be traveling in the mean time.
I really hope I can find the root cause and solve it definitely.

**Comment by guicel** [comment] 2019-05-05 19:08
I think the reset of libreelec setting solve issues. But Why ??

**Comment by Smeulf** [comment] 2019-05-05 20:11
There's too much possible reason...

For the record, LibreELEC soft reset basically removes all hidden directories in /storage

This includes :
- .config (where LE configuration is stored)
- .kodi (where Kodi conf and temporary files are stored)
- .cache

So what I want to do is to reinstall LE, hope to get the same error, backup, soft reset, configure and install again, make it work, backup, and then compare both extracted backups using GIT to determine what's different.

Unless someone find a better idea/way to catch the cause of the error...

**Comment by Smeulf** [comment] 2019-05-05 20:23
@guicel did you enabled firewall (iptable) on your setup ?

Is there some specific setting you set at initial startup ? Something special I should know about your setup to reproduce the issue ?

Thanks.

**Comment by guicel** [comment] 2019-05-05 21:13
I have no activate the firewall. I activate french language ssh samba.
nothing special i think.

**Comment by CastagnaIT** [comment] 2019-05-06 18:03
I now found out that there's a hidden .Kodi folder
before I couldn't find it, otherwise I'd have informed you first

Inside it there is a "cdm" folder with some widevine config files, it is possible that the cause is one of these corrupted files:
.challenge
.init
.response

eliminating them addon should return to work

**Comment by CastagnaIT** [comment] 2019-05-08 18:05
since you've managed to solve it, I'm closing it

**Closed by CastagnaIT** 2019-05-08 18:05 UTC

**Comment by spectroman** [comment] 2019-05-08 18:33
Well, I could not fix this... there is no "hidden" .kodi folder... not files inside a cdm folder (only the lib link to a another location with a different file... nothing like described.)

So yeah well... I don't find a solution for this neither on OSMC or LibreELEC. 

AFAIK Netflix on Kodi henceforth is permanently broken here. :(

**Comment by guicel** [comment] 2019-05-08 18:37
spectroman have you can test a reset of all setting of libreelec (in libreelec menu) and reinstall addon ?

**Comment by CastagnaIT** [comment] 2019-05-08 18:46
you can see the hidden folders by browsing the disk with a linux distribution or through a shell, not using osmc sharing system

**Comment by guicel** [comment] 2019-05-08 19:23
If the deletion of these files solves the problem, should it not be integrated into the reset of the addon's parameters ?

**Comment by Smeulf** [comment] 2019-05-08 19:27
For now, it's not confirmed this operation solves the problem, unless you could reproduce the error, delete them and solve it again ?

We just know that a LE soft resetting solves it for now.

IMHO proper tests must be run to confirm the root cause and then it can be fixed.

**Comment by spectroman** [comment] 2019-05-08 20:49
I'm here, tested all the possible combinations on LibreELEC... Incredibly for some unknown reason, the only thing u need to do is to reinstall the plugin over.. don't even need to reset the configuration.

If you install it from scratch, he will login and list everything but he will never play, always with the same error. Just reinstall the ZIP file, makes it work, kinda magically.

There are no detectable differences on the files, in the same way, there are no such files for me, as cited by @CastagnaIT 

And I know my way around linux quite well thanks, there are no such files, look:

```
##############################################
#                 LibreELEC                  #
#            https://libreelec.tv            #
##############################################

LibreELEC (official): 9.0.1 (RPi2.arm)
Acrux:~ # find . -iname .kodi
./.kodi
Acrux:~ # find . -iname cdm
./.kodi/cdm
./.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm
Acrux:~ # ls -lash ./.kodi/cdm
total 12
     4 drwxr-xr-x    2 root     root        4.0K May  8 19:44 .
     4 drwxr-xr-x    8 root     root        4.0K May  8 19:38 ..
     4 lrwxrwxrwx    1 root     root          88 May  8 19:44 libwidevinecdm.so -> /storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm/libwidevinecdm.so
Acrux:~ # ls -lash ./.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm
total 6812
     4 drwxr-xr-x    2 root     root        4.0K May  8 19:44 .
     4 drwxr-xr-x    3 root     root        4.0K May  8 19:44 ..
  6664 -rwxr--r--    1 root     root        6.5M May  8 19:44 libwidevinecdm.so
   140 -rw-r--r--    1 root     root      136.4K May  8 19:44 widevine_config.json
Acrux:/ # find .  -regex ".*cdm.*"
./storage/.kodi/cdm
./storage/.kodi/cdm/libwidevinecdm.so
./storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm
./storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm/libwidevinecdm.so
./storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm/widevine_config.json
```

There is nothing to delete. After activating it, no new files appear, after resetting no files remain... if he is reinstalled, nothing changes.. but it just works, and only on LibreELEC, it doesn't work on OSMC the same method.

wow.

**Comment by guicel** [comment] 2019-05-08 20:59
@spectroman .
On my rp3 with librelec (and the addon works)  I connect to libreelec with ssh.
mount -o remount,rw /flash
cd .kodi
cd cdm
ls
There are the 3 files.

**Comment by Smeulf** [comment] 2019-05-08 21:53
@guicel under LibreELEC, no need to remount /flash to work on /storage/.Kodi

/storage is writable by default

@spectroman there's definitely 'something' different, just need to find out 'what'.

As said, I want to compare both working and not working files using Git to determine if there's a difference.

We'll find out what's wrong, for both LE and OSMC, but it might take some time.

One thing I'm thinking right now is that background services may be running while something is missing, and reinstalling the addon restarts the service. Might be an answer for LE.

Also @spectroman, can you provide a full debug log for the problem under OSMC ? Thanks.

**Comment by Smeulf** [comment] 2019-05-14 16:56
Well, I can't reproduce the issue :/

Here with LE 9.0.1, I have no error message.

Test protocol:

- Fresh LibreELEC install on a new sd card
- Install and configure InputStream
- Install addon from last sources
- Wait for background services to start
- Logon
- Try to play an episode (Lucifer - S02E01) -> prompt for Windevine installation
- Reboot
- Play same episode : Working

Same result with OSMC, same protocol, I can't reproduce the issue, and everything is working fine here...
