### ISSUE TITLE
not able to change/create account

### ISSUE THREAD

**Issue by Spacewalker2** [CastagnaIT/plugin.video.netflix#25] opened 2019-03-14 13:56 UTC
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Attempts to enter the netflix account data.

### Addon version used
20190313

### Description
Sign off button in settings of plugin don't work. The settings dialog disappear immediately when I try to use the sign off button. The change account button is missing. Only a notification appears. Something like watch log file for further information.

### Steps to Reproduce

1. Select netflix add-on.
2. Open context menu and choose settings.
3. Choose account and select sign off.
4. Press enter.

**Expected behavior:**
Getting a dialog where I can enter my account data.

**Actual behavior:**
Setting dialog disappears.

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

I'm using a raspberry pi 3 with arch linux arm and kodi 18. I'm not sure this is notable but amazon vod plugin is working fine.

## Debug log
Logfile shows cryptodome is missing but I installed the python-cryptodome package from arch linux arm and tested it again after a reboot but nothing changed.
[kodi.log](https://paste.kodi.tv/icasasigek.kodi)

**Comment by CastagnaIT** [comment] 2019-03-14 19:07
is not a bug is intended behavior, the plugin structure has some limitations not easily solvable, so disconnect is not intended as "I want to change the account".

when you disconnect, the addon disconnects, then
when you return to the addon and try to access to any menu it will ask you your credentials, if they are different, the profiles and menus are reloaded.

I do not recommend to exchange accounts, because the episodes/movies marked as seen within kodi are currently shared

**Closed by CastagnaIT** 2019-03-14 19:07 UTC

**Comment by Spacewalker2** [comment] 2019-03-15 11:39
Solved it. I should have read the log file once more! It has to be the python2-pycryptodomex package of arch linux arm and not the python-pycryptodomex package.
