### ISSUE TITLE
viewtype (viewmode) processing error

### ISSUE THREAD

**Issue by kmc4001** [CastagnaIT/plugin.video.netflix#659] opened 2020-05-24 03:28 UTC
#### Your Environment
- Netflix add-on version: 1.3.2
- Operating system version/name: Windows 10, CoreELEC 9.2.2 (both)
- Device model:  Normal Desktop, Beelink GT1 (both)

Used Operating system:
* [ ] Android
* [ ] iOS
* [ x ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ x ] Windows

### Describe the bug

Configured the viewtypes wasn't kept.

Normal Case : No Error)
 1) execute Netflix Addon
 2) select profile
 3) select myList
 4) Configure viewtypes (ex Shift)
 5) exit kodi
 6) reppeat 1)~6)  => No problem (keep configured viewtypes)

Error Case)
 1) execute Netflix Addon
 2) select profile
 3) select myList
 4) Configure viewtypes (ex Shift)
 5) backward previous view and forward myList
     (repeat this action and don't always keep viewtypes)
 6) Error (Can't keep configured viewtypes)

#### Expected behavior

  configured viewttypes will be kept in any moving list(ex myList, continueWatching, recentlyAdded)

#### Actual behavior

  configured viewttypes wasn't kept in any moving list

#### Steps to reproduce the behavior
Normal Case : No Error)
 1) execute Netflix Addon
 2) select profile
 3) select myList
 4) Configure viewtypes (ex Shift)
 5) exit kodi
 6) reppeat 1)~6)  => No problem (keep configured viewtypes)

Error Case)
 1) execute Netflix Addon
 2) select profile
 3) select myList
 4) Configure viewtypes (ex Shift)
 5) backward previous view and forward myList
     (repeat this action and don't always keep viewtypes)
 6) Error (Can't keep configured viewtypes)

#### Possible fix

I think that saving path in the Viewtype6.db is error.

Select records in the Viewtype6.db (Specially "Path" column)

plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/?genre_id=None
plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/queue/?genre_id=None
plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/queue/queue/queue/?genre_id=None
plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/queue/queue/queue/queue/?genre_id=None
plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/queue/queue/queue/queue/queue/?genre_id=None
plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/queue/queue/queue/queue/queue/queue/?genre_id=None

When I repeat this action(backward previous view and forward myList)
Everytime new record added in the Viewtype6.db

repeat backward and forward view  ===>  continuously added "queue" path 
(ex queue/queue/queue/queue/.... )

-------------------------------

### Debug log

The debug log can be found from this link:

#### Installation
* [ x ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment] 2020-05-24 07:39
i do not see Viewtype database in kodi: https://kodi.wiki/view/Databases

in my test on kodi 19 and 18.6 there is not Viewtype database
I don't know how you get it
and i couldn't reproduce your problem

However, the add-on doesn't have direct access to Kodi's databases
the only thing that do is sends only the ID that the user enters to kodi

**Comment by kmc4001** [comment] 2020-05-24 08:49
> missing debug log,
> i do not see Viewtype database in kodi: https://kodi.wiki/view/Databases
> 
> in my test on kodi 19 and 18.6 there is not Viewtype database
> I don't know how you get it
> and i couldn't reproduce your problem
> 
> However, the add-on doesn't have direct access to Kodi's databases
> the only thing that do is sends only the ID that the user enters to kodi

Thank you for your reply.

Please check again my kodi log.

Attached my kodi log.
(https://github.com/CastagnaIT/plugin.video.netflix/files/4673171/kodi.log)

Line 1919 - DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/','2','?genre_id=None','resume:false')
Line 2061 - DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/','2','?genre_id=None','resume:false')
Line 2169 - DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/','2','?genre_id=None','resume:false')
Line 2244 - DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/','2','?genre_id=None','resume:false')
Line 2351 - DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/queue/','2','?genre_id=None','resume:false')
Line 2459 - DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/queue/queue/queue/queue/','2','?genre_id=None','resume:false')

The reason I saw Viewtype database is for finding cause that didn't keep my configuration.

The view path is repeating "queue/" as I act to forward myList view and backward profile view.

**Comment by CastagnaIT** [comment] 2020-05-24 09:33
i have installed latest kodi 18.7 nightly and tried again the steps of error case
but after 10 attempts no problems with views and there is no "queue" repeated

are you sure the steps or err case are exactly?

tested with kodi Estuary skin and i view ID 500

**Comment by kmc4001** [comment] 2020-05-24 09:56
> i have installed latest kodi 18.7 nightly and tried again the steps of error case
> but after 10 attempts no problems with views and there is no "queue" repeated
> 
> are you sure the steps or err case are exactly?
> 
> tested with kodi Estuary skin and i view ID 500

Kodi version : 18.7 (windows 10)
Skin : kodi default Skin (Estuary)

This is final asking.

I try to describe the error steps exactly.

Please check below steps one more time.

- Videos / Netflix 
 . select my Profile
- Videos / Netflix / [My Name] - Main Menu
 . select my List (click)
- TV shows / Netflix / my List
 . configure viewtype - Poster
 . press back key
- Videos / Netflix / [My Name] - Main Menu
 . press back key ( => This step is important for the steps occuring error case)
- Videos / Netflix 
 . select my Profile
- Videos / Netflix / [My Name] - Main Menu
 . select my List (click)
- TV shows / Netflix / my List
 . viewtype - List (DefaultValue. didn't kept my configuration)
 . configure viewtype - Poster 
 . press back key
(repeated steps. same result)
- Videos / Netflix / [My Name] - Main Menu
 . select my List (click)
- TV shows / Netflix / my List
 . viewtype - List (DefaultValue. didn't kept my configuration)
 . configure viewtype - Poster 
 . press back key
...

**Comment by CastagnaIT** [comment] 2020-05-24 11:28
oh now understand,
i shot the problem
before i thought you were using Views in addon settings...

and i think i fixed, please try:
[plugin.video.netflix_1.3.2_20200524_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4673380/plugin.video.netflix_1.3.2_20200524_t1.zip)

**Comment by kmc4001** [comment] 2020-05-24 13:21
> oh now understand,
> i shot the problem
> before i thought you were using Views in addon settings...
> 
> and i think i fixed, please try:
> [plugin.video.netflix_1.3.2_20200524_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4673380/plugin.video.netflix_1.3.2_20200524_t1.zip)

I'm glad that you understood and fixed it!!!!
Thank you very much^^

I tried execute fixed version
But, another error occured.

I attached screenshot and kodi.log
Maybe I think that you will fix easily ^^

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4673585/kodi.log)
![fixed_ver_error](https://user-images.githubusercontent.com/53202418/82755168-dc3cf500-9e0c-11ea-9dce-e3052ba41bdf.png)

**Comment by CastagnaIT** [comment] 2020-05-24 16:49
my bad i fixed with a solution not compatible with both kodi 18/19 versions
[plugin.video.netflix_1.3.2_20200524_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4673975/plugin.video.netflix_1.3.2_20200524_t2.zip)

**Comment by kmc4001** [comment] 2020-05-25 14:23
> my bad i fixed with a solution not compatible with both kodi 18/19 versions
> [plugin.video.netflix_1.3.2_20200524_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4673975/plugin.video.netflix_1.3.2_20200524_t2.zip)

Hi~

I confirmed that second version is well. 
Test Device : Beelink gt1, CoreELEC 9.2.2 (kodi 18.6), Estuary Skin
This is the device to use for me actually.
very very good~~~!!. viewtype setting is kept well.

But,
Another problem was discovered.
The problem is "max resolution" is 540p. 
Before I test "t2" fixed version, Max resolution is 1080p (No problem)
(Previous version in your repository published is 1.3.2)

To compare previous version,
I tried to install previous version in your repository published. I can't.
anymore there was not 1.3.2 in repository.
(Maybe you closed 1.3.2 version temporarily)

therefore, I tried to install 1.3.1 (last version in repository)
Max resolution is 540p.

I tried to reinstall "Widevind CDM", but didn't solved the problem.

I don't know why max resolution is 540p.

Can you check again this cause?
I'm so sorry it's bothering you.

I really hope to use your addon in my device (coreelec, 1080p)

**Comment by CastagnaIT** [comment] 2020-05-25 14:30
well,
for 540p there is an issue already open
affects all ARM linux devices

**Closed** 2020-05-26 12:32 UTC
Labels: Resolution: Fixed, Triage: Confirmed
