### ISSUE TITLE
Netflix background services interfere with sandmans Amazon plugin

### ISSUE THREAD

**Issue by laclaro** [CastagnaIT/plugin.video.netflix#512] opened 2020-03-10 22:37 UTC
Hi,

I got to the root of my problem (and maybe the one of others as well, see e.g. https://github.com/CastagnaIT/plugin.video.netflix/issues/451 https://github.com/CastagnaIT/plugin.video.netflix/issues/406). The addon background services somehow interfere with the background services of the amazon addon by sandmann79 (https://github.com/Sandmann79/xbmc).
* If I run kodi with amazon disabled, netflix background services come up properly.
* If amazon is enabled, background services won't come up properly. There is no "Background services started" message, but after some time/starting attempts of the netflix addon, there is no error message prompted anymore. The netflix addon fails to load (infinite loading loop without logged messages).

Which actions shall I log to clarify the behavior?

Best

Henning

**Comment by CastagnaIT** [comment] 2020-03-11 07:56
I had my suspicions about this thing
also seen the latest reports, also suspect of Addon Signals addon
but i haven't been able to figure out what's interfering

you can provide a log (instructions in the Readme) with amazon addon enabled and netflix service stuck?

**Comment by Varstahl** [comment] 2020-03-11 08:59
Hmm… I'm the maintainer of VOD only, but this is the first I hear of it. I'll keep an eye on this issue, in case there's some truth to that.

**Comment by CastagnaIT** [comment] 2020-03-11 09:04
Hi @Varstahl thanks for being here, is weird thing
but lately, also a lot of people have been complaining about timeouts errors with AddonSignals and i don't understand what's going on

**Comment by Varstahl** [comment] 2020-03-11 09:12
Well, you already know the issues with the py3 forced Kodi 19, but other than that I'm not aware of anything that should interfere with regular operations. If we're talking Kodi 18, that's strange.

**Comment by CastagnaIT** [comment] 2020-03-11 09:23
Yes i know about py3, but no problem with it,

this is a summary of the current situation:
-this is the first one that says there's a conflict between amazon and netflix
-i have noticed that all users using libreelec or linux systems distro (but always Kodi 18.x), i don't know if that would be relevant
-some other users accuse weird AddonSignals timeouts, the addon sends the request but no longer receives the answer, and the nf service is running (no errors il the logs)

**Comment by laclaro** [comment] 2020-03-11 11:33
Maybe you should request the info "amazon installed or not" from a number of suspicious issues.

**Comment by Varstahl** [comment] 2020-03-11 11:51
A question arises: is the amazon service scraping while you run netflix? Might it be a simple CPU/network resources lock?

**Comment by ccope** [comment] 2020-03-11 18:13
I've been using the HTTP-mode for the netflix addon and encountered a situation where the amazon plugin seemed to get stuck starting up its service. I had to disable the amazon plugin to keep my CPU from getting stuck at 100% on startup. This was about a month ago and I didn't have much success figuring out what exactly was happening via GDB (apologies for the lack of logs). I'm using Kodi 18 with Ubuntu 18.04 on a fairly beefy machine with 16GB of ram and an Intel Skylake CPU. I can try to reproduce it again this weekend.

**Comment by DoctorBR** [comment] 2020-03-11 18:39
This is a Linux-only problem, correct? 

This does not happen on the **Android TV** operating system on Xiaomi **Mi Box 3** (MDZ-16-AB) with **Kodi 18.6**.

**Comment by Varstahl** [comment] 2020-03-11 19:01
@ccope afaik the Amazon plugin (not Amazon VOD) does a fairly intense scraping the first run which can take hours between data scraping and db archiving. The updates should be lighter but I'm not 100% sure. It's one of the reasons why it's being dropped in the first place.

**Comment by laclaro** [comment] 2020-03-11 20:16
Testing finished:
* Amazon VOD + Netflix play nice
* Amazon w/o credentials (log: https://paste.kodi.tv/ridujelome.kodi) 
  OR installed but disabled + Netflix play nice
* Startup of Kodi Amazon with credentials + Netflix 
  (log: https://paste.kodi.tv/sejagoqugo.kodi and https://paste.kodi.tv/awasacunex.kodi) cause Netflix background services to not run. 
  On launching Netflix the error message complaining about the not running services does 
  NOT pop up.

Concerning CPU lock: the rpi3 is maxed out in one CPU when the Amazon addon is started. But this is normal for intense tasks on this system. DRM HD Movies also run completely in the CPU for Netflix/Amazon and this runs smoothly as well...

PS: If Amazon will be dropped in favor of Amazon VOD, maybe do not put too much effort here.

Best,

Henning

**Comment by Varstahl** [comment] 2020-03-11 20:30
> On launching Netflix the error message complaining about the not running services does
NOT pop up.

Does not complain because judging by the logs the service *is* running. Maybe a race condition/timeout due to the heavy load caused by the other addons?

**Comment by CastagnaIT** [comment] 2020-03-12 08:23
@Varstahl is this the code that run the update?
https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon/service.py#L76

if that's really it, it is not managed in the most exact way

in this way you delegate the operation in a frontend instance,
where instead the operation must be performed within the service instance (backend)

it is possible that this blocks the Python GIL causing the blocking of the other addons services

**Comment by Varstahl** [comment] 2020-03-12 09:37
Quite possible, but as I said I never touched that codebase which is about to be thrown out, so I'm not 100% sure. I'll report it back.

**Comment by CastagnaIT** [comment] 2020-03-21 18:59
i see that the issue https://github.com/Sandmann79/xbmc/issues/423 has been labeled as _wontfix_
and from my side i can do nothing,
then i close this issue

**Closed by CastagnaIT** 2020-03-21 18:59 UTC
