### ISSUE TITLE
Request failed validation during key exchange

### ISSUE THREAD

**Issue by jgalode** [CastagnaIT/plugin.video.netflix#677] opened 2020-05-31 12:21 UTC
#### Your Environment
- Netflix add-on version: CastagnaIT Repository for KODI 18.x LEIA - repository.castagnait-1.0.1
- Operating system version/name: Android 9
- Device model:  Beelink GT-King

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I installed the version of the netflix plugin available via the following link : https://github.com/CastagnaIT/plugin.video.netflix/

[CastagnaIT Repository for KODI 18.x LEIA - repository.castagnait-1.0.1.zip](https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.1.zip)

once the connection attempt is made, I have this error: "Request failed validation during key exchange"

what is the solution to solve this problem please ?

#### Expected behavior
launch of the Netflix plug-in and play movie

#### Actual behavior
Error

#### Steps to reproduce the behavior

1. login
2. access to the Netflix plug-in
LOG: https://paste.kodi.tv/yabomiweqo.kodi

### Additional context or screenshots/videos (if appropriate)

Youtube Video error Kodi :
[![Error Kodi: Request failed validation during key exchange](https://i.postimg.cc/TY7rTZYK/partie0.jpg)](https://youtu.be/1NzQSossEOw)

#### Pictures

android tv specification (Beelink GT-King):
![IMG_20200531_124335](https://user-images.githubusercontent.com/19157935/83351667-607c0480-a346-11ea-997c-9e2e14eaa90a.jpg)

**Comment by CastagnaIT** [comment] 2020-05-31 12:47
i need you report here a screeshot of the ESN from netflix official app by censuring only last numbers

**Comment by jgalode** [comment] 2020-05-31 13:08
@CastagnaIT

![nextflixcapture](https://user-images.githubusercontent.com/19157935/83353097-77bfef80-a350-11ea-8ec6-202fe6fa7d59.jpg)

**Comment by CastagnaIT** [comment] 2020-05-31 13:16
I understand the problem but I need more data to apply a solution suitable for everyone

so i need another thing a bit long,
i write here the steps:
1- Install Material terminal App
2- Open it, in the black screen write `getprop` (a long list must be viewed)
3- Open app options (3 dots) and select `Send by email`

You can send to: gottardo.stefano.83[at]gmail.com

**Comment by jgalode** [comment] 2020-05-31 13:38
@CastagnaIT 

I sent all of your request by email

**Comment by CastagnaIT** [comment] 2020-05-31 13:40
received,
but i not understand because of two file and two models??

**Comment by jgalode** [comment] 2020-05-31 13:48
just in case you need more information, since I took a screenshot of the Oneplus 5 😊

De : Stefano Gottardo <notifications@github.com>
Envoyé : dimanche 31 mai 2020 15:40
À : CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc : jgalode <galode@protonmail.ch>; Author <author@noreply.github.com>
Objet : Re: [CastagnaIT/plugin.video.netflix] Request failed validation during key exchange (#677)

received,
but i not understand because of two file and two models??

**Comment by CastagnaIT** [comment] 2020-05-31 13:51
No, your situation is not more clear.

your issue is opened for **Beelink GT-King**

why did you send me the screenshot of ONEPLUS?
why did you send me the prop list of ONEPLUS?

**Comment by jgalode** [comment] 2020-05-31 13:53
I answered you above : The official Nextflix application cannot be installed on the Beelink GT-KING Android TV Box. For Netflix the equipment is not supported

**Comment by CastagnaIT** [comment] 2020-05-31 14:19
is the playstore that block you?

I think it's one of the model devices on the netflix blacklist

you can try install this test
before uninstall previous and also user data when prompt:
[plugin.video.netflix_1.4.0_20200531_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4707757/plugin.video.netflix_1.4.0_20200531_t1.zip)

**Comment by jgalode** [comment] 2020-05-31 14:30
I found a solution from the apkmirror site: https://www.apkmirror.com/uploads/?q=netflix
I downloaded the Netflix version 7.58.0 build 26 34888 by Netflix, Inc. , which is a stable version.

![20200531_162052](https://user-images.githubusercontent.com/19157935/83354855-c626bb80-a35b-11ea-830d-dc3da48116a0.jpg)

@CastagnaIT I will also try your zip file

**Comment by jgalode** [comment] 2020-05-31 15:03
@CastagnaIT 

I just tested your plug-in on each video launch it makes kodi crash.

Youtube Video crash Kodi :
[![crash kodi with plug in plugin.video.netflix_1.4.0_20200531_t1](https://i9.ytimg.com/vi/kUuWp0P3xfM/mq1.jpg?sqp=CPCMz_YF&rs=AOn4CLD4mZX2FKs-CK2P8NF-ntPB5S-uxg)](https://youtu.be/kUuWp0P3xfM)

**Comment by jgalode** [comment] 2020-05-31 15:24
ESN code works fine automatically:
![20200531_171318](https://user-images.githubusercontent.com/19157935/83355941-ea39cb00-a362-11ea-927b-10a6b0487362.jpg)

here is a new LOG about the kodi crash: https://paste.kodi.tv/evoxozazed.kodi

**Comment by jgalode** [comment] 2020-05-31 15:49
@CastagnaIT 

I correctly installed the plug-in having uninstalled the other version
![20200531_174444](https://user-images.githubusercontent.com/19157935/83356497-df813500-a366-11ea-87fc-76eba43d8774.jpg)
![20200531_174539](https://user-images.githubusercontent.com/19157935/83356501-e3ad5280-a366-11ea-85d8-1408d9cae3c6.jpg)

**Comment by CastagnaIT** [comment] 2020-05-31 15:57
I doubt the crash was caused by the addon do not see nothing error related to the addon in the log
the only thing that i have changed is the esn
try reboot the device

**Comment by jgalode** [comment] 2020-05-31 16:17
I just restarted the Android TV box, and I have the same problem:

[![crash kodi with plug in plugin.video.netflix_1.4.0_20200531_t1 (part 2)](https://i9.ytimg.com/vi/_gf27T_UeQ4/mq1.jpg?sqp=CMmvz_YF&rs=AOn4CLCgL4pUVCvbVlQXJ3TuKxHkahr9Vg)](https://youtu.be/_gf27T_UeQ4)

here is a new LOG: https://paste.kodi.tv/gonoterani.kodi

**Comment by CastagnaIT** [comment] 2020-05-31 16:27
This is one of the last error:
> 2020-05-31 18:02:07.274 T:7903   ERROR: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(0)

that is an error generated by Kodi core and/or related something of your device system not from the addon

I tried use same esn with this test, but i think the crash remains:
[plugin.video.netflix_1.4.0_20200531_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4707980/plugin.video.netflix_1.4.0_20200531_t2.zip)

**Comment by jgalode** [comment] 2020-05-31 17:04
Actually the crash starts again unfortunately:

Youtube Video crash Kodi (part 3) :
[![crash kodi with plug in plugin.video.netflix_1.4.0_20200531_t2 (part 3)](https://i9.ytimg.com/vi/U9l1kyiZ4pk/mq2.jpg?sqp=CNPEz_YF&rs=AOn4CLBBl6OzIQ8BftJ93fZYaMD5i2eJAA)](https://youtu.be/U9l1kyiZ4pk)

New code ESN automatically:
![20200531_185229](https://user-images.githubusercontent.com/19157935/83358049-fa58a700-a370-11ea-8d99-b68141b580e6.jpg)

here is a new LOG: https://paste.kodi.tv/sasixujaga.kodi

**Comment by CastagnaIT** [comment] 2020-05-31 17:55
Same error, to correct that problem you have to make a report to kodi devs

i won't include my changes in the addon until you tell me that the Kodi developers have solved this crash

in the meantime i close the issue,
if you have any news in the future you can reopen it to request to include the changes

**Comment by CastagnaIT** [comment] 2020-06-03 17:10
well 
so can you do last test?
on expert settings in to Manual ESN write the same esn but change PRV-T with PRT-B
and let me know if go well and you can watch videos or result error.

after that to restore the original settings select Reset ESN.
thanks

For the TypeError need a log as always

**Comment by jgalode** [comment] 2020-06-03 17:48
kodi.log: https://paste.kodi.tv/rezaneqesu.kodi

the problem is identical with this new manually registered key:
![20200603_194218](https://user-images.githubusercontent.com/19157935/83669888-96351d80-a5d2-11ea-887e-93255afc1aae.jpg)
![20200603_193833](https://user-images.githubusercontent.com/19157935/83669954-ae0ca180-a5d2-11ea-8620-3def7deecf85.jpg)

**Comment by CastagnaIT** [comment] 2020-06-04 06:17
lolomo KeyError is out of this issue
netflix is making big changes lately use the other menus

**Comment by CastagnaIT** [comment] 2020-06-04 15:45
i officlally applied the changes to the addon,
i know i is been a log of tests...
i want to be sure that is all ok

new instrunctions here:
- Delete previous nf addon (with also user settings when prompt)
- Install this:
[plugin.video.netflix_1.4.0_20200604_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4731107/plugin.video.netflix_1.4.0_20200604_t1.zip)
- Do the login, i think after login the error appears "key excange" ecc ...
- Now open add-on Expert settings and enable `Force Widevine security level L3`
- Press Ok to save the setting changes
- Now try to play a video (from a working menu...)

thanks for your patience

**Comment by jgalode** [comment] 2020-06-05 09:45
@CastagnaIT 

1) kodi.log: https://paste.kodi.tv/hayoluzubu.kodi

2) kodi.log: https://paste.kodi.tv/lugifujaba.kodi

![Screenshot_20200605-112035](https://user-images.githubusercontent.com/19157935/83861711-38631b80-a721-11ea-9754-e5d39e820afd.png)
![Screenshot_20200605-112322](https://user-images.githubusercontent.com/19157935/83861743-444edd80-a721-11ea-8035-7057813eb768.png)

I tried with the key manually same result:
![Screenshot_20200605-112920](https://user-images.githubusercontent.com/19157935/83861767-4ca71880-a721-11ea-8e00-ba47a100cec9.png)

**Comment by CastagnaIT** [comment] 2020-06-05 16:11
in the first log have no debug so can not understand nothing
the second one unfurnately not help 🙁

I prepared new zip, use same instruction above:
[plugin.video.netflix_1.4.0_20200605_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4737267/plugin.video.netflix_1.4.0_20200605_t2.zip)

this time i have automatically enabled for you the nf verbose debug

**Comment by jgalode** [comment] 2020-06-08 14:02
I tested it works by activating the option I have netflix in standard quality

kodi.log: https://paste.kodi.tv/agizawefoq.kodi

I think the problem is solved under the Android kodi version of the beelink GT-KING

--------------------------------------------------------------------------------------------------------------

I found another way to have Netflix in 1080P and also in 4K with this tv box using your plug-in simply under CoreElec it works perfectly this way.
>> CastagnaIT Repository for KODI 18.x LEIA - repository.castagnait-1.0.1.zip <<

**Comment by CastagnaIT** [comment] 2020-06-08 14:08
you can not get 4K under CoreElec 😂
but so yes you can use CoreElec to get 1080P 😊

**Closed** 2020-06-08 14:18 UTC
Labels: Resolution: Fixed
