### ISSUE TITLE
Error "UnicodeEncodeError"

### ISSUE THREAD

**Issue by CKD38** [CastagnaIT/plugin.video.netflix#644] opened 2020-05-18 04:54 UTC
#### Your Environment
- Netflix add-on version: v1.3.1
- Operating system version/name: Windows 10
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [X] Windows

#### Expected behavior

Select program and play
#### Actual behavior

When I select program shows error message "UnicodeEncodeError"
#### Steps to reproduce the behavior

1.Select any Movie or TV Show

#### Possible fix

Does this have anything to do with the Chinese version of NETFLIX?
### Debug log

The debug log can be found from this link:[here](https://drive.google.com/file/d/1-_erumAXhwHRqhZum-sLNwirF4-sgOj0/view?usp=sharing
)
#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

#### Other information

My mi box (ANDROID) has the same problem.
#### Screenshots

![Netflix](https://user-images.githubusercontent.com/65524290/82173962-b04bdc00-9901-11ea-9438-e8aca0d92bdf.png)

**Comment by CastagnaIT** [comment] 2020-05-18 07:21
Hi
the chinese characters are because you have put the fine in a text reader with wrong decoding
you have to copy/paste to https://paste.kodi.tv/ by open file with a text editor that support various text encoding like Notepad++

try install this and let me know:
[plugin.video.netflix_1.3.0_20200518_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4642598/plugin.video.netflix_1.3.0_20200518_t1.zip)

**Comment by CKD38** [comment] 2020-05-18 08:08
Hi,
I tried to uninstall first and then install the file you provided. But the situation is still the same.(Both of windows and android)

In addition, I have been using this add-on for more than half a year. It has been working fine until yesterday I updated v1.3.0. I have tried to reinstall v.1.2.2 but it no longer works.

Click "Continu Watching" or "Rencently added" shows "key error" in v1.3.0. "My List" can be entered but the "UnicodeEncodeError" will also appear when selecting programs.
![Netflix-keyerror](https://user-images.githubusercontent.com/65524290/82189245-a508a880-9921-11ea-8e32-ee8c6b7b1fce.jpg)


Is there any information I can provide?

**Comment by CastagnaIT** [comment] 2020-05-18 08:10
you have installed:
plugin.video.netflix_1.3.1_20200518_t1.zip
or 
plugin.video.netflix_1.3.1_20200518_t2.zip
?

**Comment by CKD38** [comment] 2020-05-18 08:12
plugin.video.netflix_1.3.1_20200518_t2.zip

**Comment by CastagnaIT** [comment] 2020-05-18 08:32
i can not reproduce the issue on my system
so we have try by steps

i see also another error:
<pre>
2020-05-18 12:27:30.339 T:8424   ERROR: C:\Users\¾G???¨\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\globals.py:225: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              if path not in sys.path:
</pre>

try:
[plugin.video.netflix_1.3.1_20200518_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4642955/plugin.video.netflix_1.3.1_20200518_t3.zip)

**Comment by CKD38** [comment] 2020-05-18 08:41
The problem is still the same.
[New log](https://drive.google.com/file/d/1LQ4tqvguFJStmPT5D5NR2BRQ2Xl0i9mq/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-18 09:10
Another one, and new log
[plugin.video.netflix_1.3.1_20200518_t4.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4643147/plugin.video.netflix_1.3.1_20200518_t4.zip)

**Comment by listem62** [comment] 2020-05-18 09:14
Hi CastagnaIT ,
i have the same situations exactly in Hungary
RPI 3 KODI 18.6
Regional Hungarian
Yesterday the 1.22 version Worked fine yet.
Today Updated fine version 1.3
Login was success .
for my saved list i get unicode error
Click "Continu Watching" or "Rencently added" shows "key error" in v1.3.0. "My List" can be entered but the "UnicodeEncodeError" will also appear when selecting programs.
Thank your coperation

**Comment by CKD38** [comment] 2020-05-18 09:18
t4 does not work.
![T4](https://user-images.githubusercontent.com/65524290/82195839-755e9e00-992b-11ea-9aee-632b180ecca6.jpg)
[t4_log](https://drive.google.com/file/d/1BD5R31CqSEj29tF9jWNHQxZezfhQacFp/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-18 09:23
My bad... this error makes me crazy

[plugin.video.netflix_1.3.1_20200518_t5.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4643180/plugin.video.netflix_1.3.1_20200518_t5.zip)

**Comment by CKD38** [comment] 2020-05-18 09:35
t5 can be opened and the program can be selected without seeing "UnicodeEncodeError". 

But a new error message appears when it is about to be played.
![T5](https://user-images.githubusercontent.com/65524290/82197564-bfe11a00-992d-11ea-8c25-39667581566f.jpg)

[t5_log](https://drive.google.com/file/d/1PhmJlbopJPjEyZq3Tv6Qsgr60vkKsRcn/view?usp=sharing)

**Comment by listem62** [comment] 2020-05-18 09:37
Thank your coperation
we hope to solve the problem soon
Grazie

**Comment by listem62** [comment] 2020-05-18 09:50
Hi CastagnaIT ,
Look like for me the plugin.video.netflix_1.3.1_20200518_t5.zip
resolve the problem
RPI 3 KODI 18.6
Regional Hungarian
Grazie

**Comment by CastagnaIT** [comment] 2020-05-18 09:54
@CKD38 i do not understand the playback error but can be related to the first log error

try:
[plugin.video.netflix_1.3.1_20200518_t6.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4643332/plugin.video.netflix_1.3.1_20200518_t6.zip)

**Comment by CKD38** [comment] 2020-05-18 10:04
Same problem as t5.
[t6_log](https://drive.google.com/file/d/17LdgjOl3q07Gr9T60PoR9O2-vh_zApxv/view?usp=sharing)

**Comment by CKD38** [comment] 2020-05-18 10:16
By the way,I just tested t5 and t6 in my mi box. 
But neither can be turned on.
![IMG_0269](https://user-images.githubusercontent.com/65524290/82201900-a04cf000-9933-11ea-94d7-7a9410391d3f.jpg)

**Comment by CastagnaIT** [comment] 2020-05-18 10:53
i am little confused by last log from string coding/decoding now seem not difference and it is strange

I will try to configure windows 10 with a Chinese profile in virtual
i will let you know

**Comment by CastagnaIT** [comment] 2020-05-18 12:36
Nothing, do not know the cause but to my chinese w10 kodi do not starts...

however i found an problem, perhaps now is better:
[plugin.video.netflix_1.3.1_20200518_t7.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4644103/plugin.video.netflix_1.3.1_20200518_t7.zip)

**Comment by CKD38** [comment] 2020-05-18 13:04
t7 still the same problem.
[t7_log](https://drive.google.com/file/d/1oevvha9lgD3ZS7i9uaGx5ImeeNpPGGH_/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-18 13:25
one error is now fixed
bot in your last log the nf debug info are disabled so i cant analyze nothing

i have added some other debug info
install this and before enable nf verbose debug,
after reboot kodi then reproduce problem and extract log
[plugin.video.netflix_1.3.1_20200518_t8.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4644298/plugin.video.netflix_1.3.1_20200518_t8.zip)

**Comment by CKD38** [comment] 2020-05-18 13:32
My bad. I didn't notice that.

t8 has the same problem.
[t8_log](https://drive.google.com/file/d/1Uv-UlxiIGKIpE9nNybcPO5ZTZFSywSGV/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-18 14:17
now i see the error:
`urlopen error [Errno 10049]`

it is strange that happen only on play
this can means that the call not reach the Cache http server

follow is not a fix, only to debug:
[plugin.video.netflix_1.3.1_20200518_t9.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4644599/plugin.video.netflix_1.3.1_20200518_t9.zip)

could be that you have custom rules to localhost loopback?

can you give me the IP output from this command?:
from CMD console window type and execute:
`ping localhost -4`

**Comment by CastagnaIT** [comment] 2020-05-18 14:18
on android should be workin

**Comment by CKD38** [comment] 2020-05-18 16:43
IP is 127.0.0.1
And the new message comes out.
![t9](https://user-images.githubusercontent.com/65524290/82235243-09992700-9965-11ea-81d9-05dce41c73de.jpg)
[t9_log](https://drive.google.com/file/d/1i3tqYOChXED_EbMgRPkwx6PaiLKXy0Xp/view?usp=sharing)

By the way, after reinstalling Kodi in my mi box, the Netfix add-on (1.3.1_20200518_t7) works. But after reinstalling Kodi on windows, the problem still exists.

**Comment by CastagnaIT** [comment] 2020-05-18 19:17
The error viewed is not important,
due to the chinese special characters i dont know how handle the code to display of the error message and i do not found any help how to do

Perhaps the error is viewed correctly with this test, but i not sure
[plugin.video.netflix_1.3.1_20200518_t10.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4646016/plugin.video.netflix_1.3.1_20200518_t10.zip)

howewer the error is always the same, so this:
`<urlopen error [Errno 10049] ??®e???ҭn¨D????§}????½T¡C>`

that can means some problem with localhost loopback network in your machine
as said before: could be that you have custom rules to localhost loopback?
or something else is changed to your system that cause the problem

to add-on side there are no changes to type of communication, in all versions use same system

**Comment by CKD38** [comment] 2020-05-18 23:54
I opened the log and found Errno 10049, but what I saw on my computer was garbled just like you.
In addition, I never custom rules to localhost loopback.

[t10_log](https://drive.google.com/file/d/1WXBm0HlNTE00MEm6b4GgHNyVVcTIJwa_/view?usp=sharing)
![t10](https://user-images.githubusercontent.com/65524290/82269993-ee024080-99a5-11ea-9382-c88c3dfec6e0.jpg)

**Comment by CastagnaIT** [comment] 2020-05-19 07:40
Another two attempt:

1)
If your computer is always on 24/7, reboot the pc

Open CMD console, and write `ipconfig /flushdns`
If you have particular security antivirus/firewall try disable it

Update addon with this, and see what happen:
[plugin.video.netflix_1.3.1_20200519_t11.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4648847/plugin.video.netflix_1.3.1_20200519_t11.zip)

if not works, reboot Kodi, and, keep Kodi software opened in windowed mode,
then at same time, open debug log text and find the string "[CACHE] Picked Port: xxxx"
take note of number "xxxx" port

Now we check the state of the server address:
On CMD console write: `netstat -na` and find the "xxxx" port
write here the line

2) IF THE -1- FAILS
In this test i have exposed the addon server to all network interfaces:

[plugin.video.netflix_1.3.1_20200519_t12_EXPOSED.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4648900/plugin.video.netflix_1.3.1_20200519_t12_EXPOSED.zip)

this is not good to do, so we use it only to understand if this works or not

**Comment by CKD38** [comment] 2020-05-19 08:22
1.
I followed your steps but it didn't work.Port is 53459.
![01 53459cmd](https://user-images.githubusercontent.com/65524290/82302522-49572180-99ec-11ea-93a5-dacc733988b6.jpg)

2.
t12 also didn't work.
![t12](https://user-images.githubusercontent.com/65524290/82302833-b36fc680-99ec-11ea-8c90-e7fefcdc04d5.jpg)
[t12_log](https://drive.google.com/file/d/1YaAc0Fse0vAL2A0-LMN4gaQAUGyM3STj/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-19 08:32
I can't figure out what's wrong with your computer
it is very strange that also if exposing the addon servers to all networks not works

i have no other solutions

**Comment by CastagnaIT** [comment] 2020-05-19 08:35
i see now the screenshot
![image](https://user-images.githubusercontent.com/3257156/82304216-53f9c280-99bc-11ea-8ce2-28cc30cee833.png)

and all localhost addresses are wrongs
you have localhost issues on your pc

**Comment by CKD38** [comment] 2020-05-19 08:50
192.168.0.14 is the IP address I set reserved for the desktop computer in the wireless AP. Both my computer and the Mi box are set to connect to the desktop computer server to watch movies and share progress. Will this have any effect?

**Comment by CKD38** [comment] 2020-05-19 09:03
I think I understand what you mean.
I will try to figure out what settings are causing this problem.

**Comment by CastagnaIT** [comment] 2020-05-19 09:55
when you have time,
can you see if the error
<urlopen error [Errno 10049] ??®e???ҭn¨D????§}????½T¡C>
if viewed correctly to nf window? and give a log?

[plugin.video.netflix_1.3.1_20200519_t12.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4649613/plugin.video.netflix_1.3.1_20200519_t12.zip)

**Comment by CKD38** [comment] 2020-05-19 13:16
[t12_1_log](https://drive.google.com/file/d/17nlNbhZoE5CBQcbQDGUtzZhoxbR9NUFf/view?usp=sharing)
I don't see this error in the LOG

**Comment by CastagnaIT** [comment] 2020-05-19 13:21
and on netflix window how you see the error?
can take screen?

**Comment by CastagnaIT** [comment] 2020-05-19 13:29
Often the localhost problems on windows are on "hosts" file

you can try again?
[plugin.video.netflix_1.3.1_20200519_t13.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4650726/plugin.video.netflix_1.3.1_20200519_t13.zip)

**Comment by CKD38** [comment] 2020-05-19 14:03
t12 and t13 show the same error message.
![t13](https://user-images.githubusercontent.com/65524290/82335628-32302800-9a1c-11ea-9b36-a427033b9560.jpg)
[t13_log](https://drive.google.com/file/d/1su9Tri_OdIbDYAy91SdJxQylfbauqXVZ/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-19 14:11
now i have added all common type of text encoding...
i hope at least one is right

[plugin.video.netflix_1.3.1_20200519_t14.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4650993/plugin.video.netflix_1.3.1_20200519_t14.zip)

**Comment by CKD38** [comment] 2020-05-19 14:21
New error mesage!
I'm sure that background service has started.
![t14](https://user-images.githubusercontent.com/65524290/82337815-c0a5a900-9a1e-11ea-9b10-69266ad9287c.jpg)
[t14_log](https://drive.google.com/file/d/1juN78kk8yVbPn5xcCKUjZHRumv9qVvAJ/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-19 14:34
Now should view the right error message on screen and log

[plugin.video.netflix_1.3.1_20200519_t15.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4651116/plugin.video.netflix_1.3.1_20200519_t15.zip)

**Comment by CKD38** [comment] 2020-05-19 15:12
When I press "Play" only shows error.
![t15](https://user-images.githubusercontent.com/65524290/82343978-13369380-9a26-11ea-945e-2e3a1c514049.jpg)
[t15_log](https://drive.google.com/file/d/15gMFc4TbpRIna3-qljJyigI55EErxyEL/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-19 15:37
kodi refused to print the error in log... do not know why i thing your language is a problem with text encoding

i think this is last try, it's a nightmare making things work in your systems with symbolic languages
[plugin.video.netflix_1.3.1_20200519_t16.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4651494/plugin.video.netflix_1.3.1_20200519_t16.zip)

**Comment by CKD38** [comment] 2020-05-19 15:54
t16 shows new error message.
![t16](https://user-images.githubusercontent.com/65524290/82348467-8262b680-9a2b-11ea-8f1e-47b2b828fa01.jpg)
[t16_log](https://drive.google.com/file/d/1f5qcco8v2DuOR7jPu8ILGeHs_DS5Il_3/view?usp=sharing)

Thank you very much for your time and effort.

**Comment by CastagnaIT** [comment] 2020-05-19 15:57
the last attempt was successful
we were lucky...😌

now you have to fix your localhost

**Comment by wagnerch** [comment] 2020-05-19 20:46
What is the result of these commands:
ping 127.0.0.1
ping ::1
ping localhost
route print
netsh int ipv4 show interfaces
netsh int ipv4 show ipaddresses level=verbose


You might want to take a look at %WINDIR%\System32\drivers\etc\hosts and see what is going on in there.  Normally all the entries are commented out on a Windows box.

**Comment by CKD38** [comment] 2020-05-20 02:14
@wagnerch 
![ping](https://user-images.githubusercontent.com/65524290/82397189-6f2f0580-9a82-11ea-898a-d20b3832d0ff.jpg)
![RP](https://user-images.githubusercontent.com/65524290/82397194-72c28c80-9a82-11ea-9876-2a0559320a68.jpg)
![NI](https://user-images.githubusercontent.com/65524290/82397197-7524e680-9a82-11ea-924d-9c876aecff6a.jpg)
![NV](https://user-images.githubusercontent.com/65524290/82397207-78b86d80-9a82-11ea-8136-cd3f44bc10b9.jpg)
![HOST](https://user-images.githubusercontent.com/65524290/82397213-7bb35e00-9a82-11ea-9ab3-acedfe4bd369.jpg)

**Comment by CastagnaIT** [comment] 2020-05-20 12:21
The main error of the issue is fixed

I leave the issue post open for a few days, to see if anyone can help you with localhost problem

**Comment by wagnerch** [comment] 2020-05-20 21:27
@CKD38 

If you have a python install, it would be interesting to see what is returned with this:
1. Run python, should bring up an interactive interpreter
2. Paste in the following
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind(('127.0.0.1', 0))
sock.getsockname()
sock.close()
3. Should return a tuple of ('127.0.0.1', random port number)

Like this:

Python 2.7.15 (default, May  4 2018, 07:50:01)  [GCC 7.3.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> sock.bind(('127.0.0.1', 0))
>>> sock.getsockname()
('127.0.0.1', 50506)
>>> sock.close()
>>>

If the python code returns an IP other than 127.0.0.1, then that might be a potential option for CastagnaIT to look at using the address returned from the bind call when calling the internal services.

One simple thing you could try is removing all of the entries in your hosts file, but I doubt that is the cause.  Your routing table suggests the only interface that could reach 127.0.0.1 is the loopback interface, but who knows with Windows.  It's a strange beast.  My personal guess here is the VMware adapters could be the cause, but I base that on nothing factual.  :)

What we know is the bind() call is binding to the wrong IP, so I am hoping getsockname() will actually tell us the IP it binded the socket to.

**Comment by ccope** [comment] 2020-05-20 23:18
I see there also appears to be a VPN configured on the machine. Sometimes the VPNs do weird things to network devices and routing tables.

**Comment by CastagnaIT** [comment] 2020-05-21 06:31
@wagnerch i do not think he is a python developer
so is better make thing easier
- Install python https://www.python.org/downloads/
- Copy this file in a folder like C:\myfile\ 
[runget.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/4660896/runget.txt)
- Open CMD console and go to folder C:\myfile\
- Type `py runget.txt`

paste here the output

**Comment by CKD38** [comment] 2020-05-21 08:14
@wagnerch @CastagnaIT Thanks for your help, the following is a screenshot of the output.
![PY](https://user-images.githubusercontent.com/65524290/82538315-25c3e080-9b7e-11ea-97cd-4d25a9a2a05b.jpg)

**Comment by CastagnaIT** [comment] 2020-05-21 11:51
I have do the same with the addon,
if you install this, in the log you can find various "ADDRESS: xxx" outputs for each sever
[plugin.video.netflix_1.3.2_20200521_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4662267/plugin.video.netflix_1.3.2_20200521_t1.zip)

so we can see if are the same

**Comment by CKD38** [comment] 2020-05-21 14:28
The error message is the same as t16.
[1.3.2_t1_log](https://drive.google.com/file/d/114WQuZpQruHRD6wrDTA0wKI1L6BKxKJ6/view?usp=sharing)

**Comment by CastagnaIT** [comment] 2020-05-21 14:35
@wagnerch as you can see
the same method but inside Kodi return the IP of computer instead the localhost address
> ADDRESS: 192.168.0.14

**Comment by CastagnaIT** [comment] 2020-05-21 14:36
@CKD38 have you VPN or PROXY enabled?

**Comment by wagnerch** [comment] 2020-05-21 21:06
@CastagnaIT Yeah, but how would you know binding to loopback isn't going to work?  As you mentioned using 127.0.0.1 is more secure than binding to the NIC interface, and I don't think the services have any ACLs or authentication.  Of course you would probably have to nmap the box, and figure out what the ports are for, if there is no firewall on the computer.

@CKD38
I know Windows has a concept of filter drivers, and I know there are NDIS filters (Network card), but I don't know if can do something like this, you can list NDIS filter drivers by using the "Get-NetAdapterBinding" cmdlet in PowerShell.  But I don't think it is necessarily showing you the order of the filter drivers, they can be chained as I recall.  But I bet there is something in there for VMware or the VPN adapter.

**Comment by CKD38** [comment] 2020-05-22 02:14
@CastagnaIT 
I tried all of them, but it didn't work.

@wagnerch 
I have removed vmware yesterday, but as you can see, the problem remains unchanged.

**Comment by CastagnaIT** [comment] 2020-05-22 06:56
@wagnerch i am not network engineer i do not know things you mentioned
i will stop here

but is a bit strange that py interpreter out kodi return the right localhost address
and py interpreter encapsulated in Kodi return a wrong address

To be safe i would delete all Kodi data, by deleting Kodi folder:
`C:\Users\[user name]\AppData\Roaming\Kodi`

And also install latest Leia build from:
http://mirrors.kodi.tv/nightlies/windows/win64/Leia/

**Comment by wagnerch** [comment] 2020-05-22 09:11
@CastagnaIT Ahh, I see so you modified the code to show the address from getsockname().  I completely missed that update.  Well, that at least means we could use that address in the server calls.  I was thinking instead of setting <service>_service_port maybe set <service>_service_addr with the full tuple from getsockname() and then use that full ip + port in the service calls.

Something like this (assuming select_unused_port returned the tuple):
> host, port = select_unused_port()
>  g.LOCAL_DB.set_value('{}_service_addr'.format(service.lower()), '{}:{}'.format(host, port))
.
.
.
> url = 'http://{}/{}'.format(g.LOCAL_DB.get_value('cache_service_addr', '127.0.0.1:8002'), callname)

The internal services are already binding to a public interface, this would just allow the plugin to work.


I am baffled too, I don't quite understand it.  Perhaps Kodi is overridding how Python or Winsock API behaves, which would make sense why Python under Kodi behaves differently than outside of Kodi.  I skimmed through the Kodi source code and couldn't really see anything where they were hooking Winsock API or patching Python to change the behavior.



@CKD38 Nothing in advancedsettings.xml for hosts entries?

https://kodi.wiki/view/Advancedsettings.xml#hosts

**Comment by CastagnaIT** [comment] 2020-05-22 11:08
> Ahh, I see so you modified the code to show the address from getsockname(). I completely missed that update. Well, that at least means we could use that address in the server calls. I was thinking instead of setting _service_port maybe set _service_addr with the full tuple from getsockname() and then use that full ip + port in the service calls.

if it was a problem encountered by many users it would make sense

I don't want to risk causing problems for more than hundreds of people, for a single user who has strange problems with his computer

the add-on works on many different operating systems, a change of this kind could compromise hundreds of users

**Comment by CastagnaIT** [comment] 2020-05-22 11:13
could try using Kodi 19 to see if the problem go away
then install the kodi 19 addon version from dailybuilds:  https://bit.ly/citnfdailybuilds

**Comment by wagnerch** [comment] 2020-05-22 18:21
@CastagnaIT Yep, makes sense to me.  I believe Amazon VOD add-on does the same thing.

@CKD38 You might want to post your question over on the Kodi Forums.  Since this behavior is happening under Kodi and not Python stand-alone.  One of the dev's there might be able to point you to an exact cause or reason.

**Closed** 2020-05-30 12:51 UTC
Labels: Resolution: Fixed
