### ISSUE TITLE
Plugin HTTP Error - 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by stefano-salari** [CastagnaIT/plugin.video.netflix#1428] opened 2022-09-27 21:49 UTC
### Netflix add-on version

1.12.14

### Operative systems used

LibreELEC

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

When the plugin is open and it should show the list of media content, it returns the error:
`404 Client Error: Not Found for url: https://www.netflix.com/api/shakti/vedfdb694/pathEvaluator?materialize=false&original_path=%2Fshakti%2Fvedfdb694%2FpathEvaluator&categoryCraversEnabled=false&isVolatileBillboardsEnabled=true&isTop10Supported=true&routeAPIRequestsThroughFTL=false&withSize=false&drmSystem=widevine`

Note: Authentication key is used as authentication method. The plugin worked fine yesterday but today got this error. Rebooting the system nor re authenticating did not solve the problem.

### Steps to reproduce the behavior

1. Go to Add-on and open Netflix addon
2. The account main menu is shown, with the account name and the "Children" menu items.
3. Click on the account name to access the content -> The "404 Client Error: Not Found for url" is returned

### Debug log - mandatory

https://paste.kodi.tv/bacicebiko.kodi

**Comment by Goorzhel** [comment] 2022-09-28 03:05
Dupe of #1425?

**Comment by daktak** [comment] 2022-09-28 04:51
Updating from 1.18.1 to 1.18.10 worked for me

**Comment by CastagnaIT** [comment] 2022-09-28 05:53
despite different error shown at screen it is same problem of #1425

**Comment by stefano-salari** [comment] 2022-09-28 07:26
Thanks guys!

I saw https://github.com/CastagnaIT/plugin.video.netflix/issues/1425 yesterday before opening this one but I didn't realise that it could be the same.

Do you want me to put these info in the https://github.com/CastagnaIT/plugin.video.netflix/issues/1425 or will you merge them together?

**Comment by CastagnaIT** [comment] 2022-09-28 07:40
we keep this one open as well, having a different error name will redirect users to the right thread,
preventing someone else from opening another issue like this again

**Comment by maddavo** [comment] 2022-10-01 04:49
Is this also causing this error that is suddenly occuring this morning for me?
![20221001_141500_resized](https://user-images.githubusercontent.com/1432875/193393075-a69b14af-84e7-493f-96f1-67e672630cbe.jpg)

**Closed** 2022-10-04 07:21 UTC
Labels: Bug, Triage: Confirmed
