### ISSUE TITLE
Queue item do nothing (...and misc)

### ISSUE THREAD

**Issue by elbowz** [CastagnaIT/plugin.video.netflix#199] opened 2019-09-09 16:27 UTC
#### Platform
0.15.2 on Kodi 18.4 on Ubuntu 19.04

#### Log
https://pastebin.com/FtzKbxM1

#### Issue
In the Kody library, clicking on "Queue item" by context menu don't add nothing to current playlist.

Instead "Play next", add all displayed items, also the previous ones (above the selected).

Ciao!

Sorry for my English

Edit:

I have found anothers issues
* The resume movie works only on a single file at once, and stop working also on this one after Kodi restart.
* Adjust refresh rate seems set wrong refresh rate (ie. 24fps => 60 Hz)

Know if there are these issues only on my setup enviroment could be a step ahead for me.

Thanks for your wonderful plugin and hard work!

**Comment by Smeulf** [comment] 2019-09-09 17:19
For the "Queue Item", it's seems it's a Kodi issue. If you try to queue a STRM file containing something like "plugin://" it's not added. I tried with Youtube plugin too, same issue.

For "Play Next" I don't even understand what it should do lol.

"Play From Here" enques all items in the container, but plays the right item first, then all following. The behavior is the same if you use the library with local files or with exported items from the addon.

> The resume movie works only on a single file at once, and stop working also on this one after Kodi restart.

Can you please describe the steps to reproduce the issue? I can't understand what you mean.

> Adjust refresh rate seems set wrong refresh rate (ie. 24fps => 60 Hz)

See https://github.com/CastagnaIT/plugin.video.netflix/issues/197

**Comment by elbowz** [comment] 2019-09-09 17:43
> For the "Queue Item", it's seems it's a Kodi issue. If you try to queue a STRM file containing something like "plugin://" it's not added. I tried with Youtube plugin too, same issue.

It's time to open a Kodi issue :)
I think could be quite usefully for the TV series.

> For "Play Next" I don't even understand what it should do lol.
> 
> "Play From Here" enques all items in the container, but plays the right item first, then all following. The behavior is the same if you use the library with local files or with exported items from the addon.

My bad, I mean "Play From Here"...and this exactly what happened. And it's right!
 I have reported only to make a compare with "Queue Item".

> > The resume movie works only on a single file at once, and stop working also on this one after Kodi restart.
> 
> Can you please describe the steps to reproduce the issue? I can't understand what you mean.

1. Enter in movie library
2. Select/play a film (of course Netflix source)
3. Go ahead with forward control
4. Stop
5. Reopen the film => resume dialog appear and ask if I want restart or resume (right behavior)

If instead of point 5 I play another film, stop and try to reopen the first one the "resume function" not works.

I have just noticed that on main windows (without enter in the movies) "resume function" never works (also re-selecting the latest film).

I see there is some workaround to allow this works...maybe something related?!


Hey thanks a lot for your answers!

**Comment by elbowz** [comment] 2019-09-09 17:49
> > Adjust refresh rate seems set wrong refresh rate (ie. 24fps => 60 Hz)
> 
> See #197

Mmhhh...I don't think is the same. 
In my case (Linux machine) when I play video at 24 fps Kodi switch at 60 Hz!
So, there is a mismatch between Netflix video fps and Hz set by Kodi.

I guess will be better if I attach a log file related to this issue.

**Comment by Smeulf** [comment] 2019-09-09 17:51
> I think could be quite usefully for the TV series

You may want to try 'up next' add-on ;)

For the resume movie, did you enable 'resume workaround' in the add-on settings? I'm not sure it's enable by default. I'll take a look.

**Comment by elbowz** [comment] 2019-09-09 17:54
I have read about 'up next' add-on and I think is a great feature. ...but playlist is different :)

For the resume, I have see the option in the settings, and is enabled (by default). I also try to enable/disable without luck.

**Comment by elbowz** [comment] 2019-09-10 10:06
> The resume workaround works fine here on Windows 10/Kodi 18.4.
> 
> Can you please:
> 1a - Enable kodi debug, and restart kodi
> 1b- Play a movie, go forward, stop
> 1c - Restart kodi again and try to resume the movie. -> save the log to log1

https://pastebin.com/vz6pGbqU
I have append the first log to the second one (kodi restarted)

> 2nd test:
> 2a - Still with debug on, restart kodi again
> 2b - Play a different movie, go forward, stop
> 2c - Play an another third movie, stop
> 2d - Try to resume the movie frop step 2a -> save log to log2

https://pastebin.com/WhLQbzW6
This is a single log execution

**note:**
I have used a second PC, but always a Linux machine: 
ArchLinux 5.2.11-arch1-1-ARCH
obviously, same issue.

On this machine the "adjust refresh rate" issue (24fps => 60Hz), could not be reproduced because monitor do not support 24 Hz...I'll open a new issue in future, also for avoid to confuse and misc all stuff.

I'll be away for 10 days, so take all your time :)

Thanks  a lot!

**Comment by Smeulf** [comment] 2019-09-10 14:20
Now I understand what's your problem with the resume workaround.

Your source is `special://profile/addon_data/plugin.video.netflix/movies/` but we're trying to find the video in the library containing the translated path `/home/muttley/.kodi/userdata/addon_data/plugin.video.netflix/movies/`

So I have to find a clean way to solve this then in case it's a special source, check in both special and translated directories.

**Comment by elbowz** [comment] 2019-09-10 15:19
> Now I understand what's your problem with the resume workaround.
> 
> Your source is `special://profile/addon_data/plugin.video.netflix/movies/` but we're trying to find the video in the library containing the translated path `/home/muttley/.kodi/userdata/addon_data/plugin.video.netflix/movies/`

**You have catch it!! :)**
I have added movies source as absolute path and all works like a charm!

Anyway, `special://` is the default location for save strm file in netflix plugin (?!)...so I have only leave untouched and added the same in the movie source :)

I have not well figure out your explanation, but `/home/muttley/.kodi/userdata/addon_data/plugin.video.netflix/movies/` is the right path (correct `special://` translation).

> So I have to find a clean way to solve this then in case it's a special source, search in both special and translated directories.

I see you have already commit a patch...so thanks!! :)

**Comment by Smeulf** [comment] 2019-09-10 15:25
> so I have only leave untouched and added the same in the movie source :)

That's what I thought, you added it manually, not using the Kodi GUI and 'browse' button :p

I didn't implemented it yet because I couldn't find it in the GUI. But Kodi wiki says the special protocol can be used in sources, so must be added.

**Comment by elbowz** [comment] 2019-09-10 16:17
> > so I have only leave untouched and added the same in the movie source :)
> 
> That's what I thought, you added it manually, not using the Kodi GUI and 'browse' button :p

Yeah...I have thought was a more clean solution...maybe no ;)

> I didn't implemented it yet because I couldn't find it in the GUI. But Kodi wiki says the special protocol can be used in sources, so must be added.

"must be added" in the kodi "core" or in your plugin?

**Comment by Smeulf** [comment] 2019-09-10 17:08
> "must be added" in the kodi "core" or in your plugin?

Special protocol for sources must be handled correctly by this add-on, as it's allowed by Kodi. That's the purpose of my PR :)

> Yeah...I have thought was a more clean solution...maybe no ;)

As Kodi allows it, there's no better or worse solution ;) Let's now wait the PR is merged.

> About the issue of "Adjust refresh rate (ie. 24fps => 60 Hz)"

Glad you found the "why", even if we can't really fix it.

**Comment by elbowz** [comment] 2019-09-10 17:39
> > "must be added" in the kodi "core" or in your plugin?
> 
> Special protocol for sources must be handled correctly by this add-on, as it's allowed by Kodi. That's the purpose of my PR :)
> 
> > Yeah...I have thought was a more clean solution...maybe no ;)
> 
> As Kodi allows it, there's no better or worse solution ;) Let's now wait the PR is merged.

Great! Thanks again for your help and PR!

> > About the issue of "Adjust refresh rate (ie. 24fps => 60 Hz)"
> 
> Glad you found the "why", even if you can't really fix it.

I have fixed it! 
You have to add a `advancedsettings/adjustrefreshrate` key to match fps with refresh.

Ciao!

**Closed** 2019-09-19 18:38 UTC
