### ISSUE TITLE
Netflix addon deletes all my Kodi library, includind libraries from another addon

### ISSUE THREAD

**Issue by masca90021** [CastagnaIT/plugin.video.netflix#888] opened 2020-10-06 15:30 UTC
Hi,

The Netflix addon is causing libraries to be purged. Jellyfin library is completely wiped at every library cleanup that the netflix addon does. I disabled the auto-update feature for tv shows seasons and episodes and everything is ok.

This is all the info: https://github.com/jellyfin/jellyfin-kodi/issues/375 

Using the latest Kodi Leia build, win 10 and haven't installed any new software in ages. Everything was ok until a couple weeks ago. Maybe this issue can be fixed without disabling that option in settings.

It's 100% confirmed that this setting is purging the library when active: "Auto-update for tv shows seasons and episodes"

**Comment by masca90021** [comment] 2020-10-06 15:36
Hi,

The Netflix addon is causing libraries to be purged. Jellyfin library is completely wiped at every library cleanup that the netflix addon does. I disabled the auto-update feature for shows and movies and all is ok.

This is all the info: https://github.com/jellyfin/jellyfin-kodi/issues/375 

Using the latest Kodi Leia build, win 10 and haven't installed any new software in ages. Everything was ok until a couple weeks ago. Maybe this issue can be fixed without disabling that option in settings.

**Comment by CastagnaIT** [comment] 2020-10-06 16:42
you want to say that i should avoid use this kodi feature (clean database) because Jellyfin not works well ?!
any add-on can call the database cleaning to remove the non existing items not only this addon

**Comment by masca90021** [comment] 2020-10-06 16:45
Yep, this kodi feature purges library items for every addon that is streaming ( jellyfin, plex, emby ). The database is not on the pc that kodi is installed resulting in this deletion. Ty for your reply.

**Comment by CastagnaIT** [comment] 2020-10-06 16:50
plex? you mean dlna server?

**Comment by masca90021** [comment] 2020-10-06 16:52
Yes. Plex, Jellyfin and Emby are DLNA servers and I have Jellyfin setup so I can watch my shows even when I am away with work in other cities or countries.

**Comment by CastagnaIT** [comment] 2020-10-06 16:56
next days i will try plex by installing it in local on my station to better understand this

**Comment by masca90021** [comment] 2020-10-06 16:58
You don't need to remove this feature, just set it to disabled by default, not to scheduled - daily. Install Jellyfin because atm I have used Jellyfin in the last 6 months. I set it to disabled and all is fine, no need to completely remove it.

**Comment by Nickiuan** [comment] 2020-10-08 07:37
Same problem, now disable option auto updated, but content in netflix still empty, how can i restore it back?

**Comment by gersilex** [comment] 2020-10-09 00:28
I have this issue as well and was able to reproduce it with a combination of different video plugins that handle the databases differently.

Video Addons: Netflix, Jellyfin, OpenMeta

The Netflix addon generates [STRM files ](https://kodi.wiki/view/Internet_video_and_audio_streams#The_.STRM_file_method:), Jellyfin and OpenMeta put entries directly into the Kodi Database.

When a cleanup is triggered by either the Kodi Library Settings' "Cleanup" or the Netflix Library Update Now button (which seems to trigger the cleanup just like I do in the Kodi Library Settings) the Cleanup does its job. And that job is to remove all files that have no file available. Because the STRM files physically exist, they do not get removed. All the entries out of thin air by Jellyfin and OpenMeta are removed. Just like the Cleanup said.

So I think there is not really a real *problem* here, other than a feature request to give add an option to skip the cleanup part of the update routine.

I think disabling it would mean that Content officially removed from Netflix would remain in the Kodi Database. Are there any other implications I don't see here?

Hope I could clear things up a little and I'm open and ready to provide more info.

**Comment by masca90021** [comment] 2020-10-09 04:22
Nice that you took the time to investigate qnd report all this back. Maybe this will better help the developer of this great addon.

**Comment by CastagnaIT** [comment] 2020-10-10 07:49
> I think disabling it would mean that Content officially removed from Netflix would remain in the Kodi Database. Are there any other implications I don't see here?

exactly if you do not run the Clean, all deleted items remains visible and broken in kodi library,
otherwise to fix this we have to use the jsonRPC calls for the removal of each single library file
this could be a slow job and if i remember correctly, it also has another problem, which while doing this, it shows the loading screen. So if you are watching a movie and in same time this operation is performed you will be interrupted until it is completed...

Analyzing Kodi's source codes, there seems to be a theoretical possibility to modifiy the Clean function to add a parameter 
to allow cleaning only within a certain path (eg netflix folder) as with the Scan function, this could solve all problems at the root, but would be applicable only to Kodi 19 because Kodi 18 is EOL.

FWIK there is no clean solution at moment

i have tried to install jellyfin but i am not able to add to kodi library the videos,
i have follow the instructions (also install plugin in server side) but after configured the addon (select server pw and addon or native) the tvshows are not listed in the kodi library?!? what step i missing?

**Comment by gersilex** [comment] 2020-10-11 14:45
> Analyzing Kodi's source codes, there seems to be a theoretical possibility to modifiy the Clean function to add a parameter
to allow cleaning only within a certain path

Not what you talk about this, I think exactly this happens already in Leia, when you delete a library folder. A popup asks if I want to remove the library data from this path.

Here are my working settings for jellyfin. I also installed the kodi companion. This is only necessary to have kodi sync watched shows back to the jellyfin server. You must be able to see the tvshows even without the companion, but it won't hurt, either.

```xml
# cat .kodi/userdata/addon_data/plugin.video.jellyfin/settings.xml 
<settings version="2">
    <setting id="additionalUsers" default="true"></setting>
    <setting id="askCinema" default="true">false</setting>
    <setting id="backupPath" default="true"></setting>
    <setting id="compressArt" default="true">false</setting>
    <setting id="connectMsg">true</setting>
    <setting id="dbSyncScreensaver">true</setting>
    <setting id="deleteMovies" default="true">false</setting>
    <setting id="deleteTV" default="true">false</setting>
    <setting id="deviceName" default="true">Kodi</setting>
    <setting id="deviceNameOpt" default="true">false</setting>
    <setting id="devMode" default="true">false</setting>
    <setting id="displayMessage">4</setting>
    <setting id="enableAddon">true</setting>
    <setting id="enableCinema">true</setting>
    <setting id="enableContext">true</setting>
    <setting id="enableContextDelete">false</setting>
    <setting id="enableContextTranscode">true</setting>
    <setting id="enableCoverArt">true</setting>
    <setting id="enableExternalSubs">true</setting>
    <setting id="enableMusic">true</setting>
    <setting id="getCast" default="true">false</setting>
    <setting id="groupedSets" default="true">true</setting>
    <setting id="idMethod" default="true">0</setting>
    <setting id="ignoreSpecialsNextEpisodes" default="true">false</setting>
    <setting id="kodiCompanion">true</setting>
    <setting id="LastIncrementalSync">2020-10-11T14:32:58z</setting>
    <setting id="limitIndex">15</setting>
    <setting id="limitThreads">3</setting>
    <setting id="logLevel">1</setting>
    <setting id="markPlayed">90</setting>
    <setting id="maskInfo">true</setting>
    <setting id="MinimumSetup" default="true"></setting>
    <setting id="MusicRescan" default="true">false</setting>
    <setting id="newContent">true</setting>
    <setting id="newmusictime">2</setting>
    <setting id="newvideotime">5</setting>
    <setting id="offerDelete" default="true">false</setting>
    <setting id="offlinetMsg">false</setting>
    <setting id="platformDetected" default="true">LibreElec</setting>
    <setting id="playFromStream">false</setting>
    <setting id="playFromTranscode" default="true">false</setting>
    <setting id="restartMsg">true</setting>
    <setting id="resumeJumpBack">10</setting>
    <setting id="server">http://jellyfin</setting>
    <setting id="serverName">Jellyfin</setting>
    <setting id="skipContextMenu" default="true">false</setting>
    <setting id="skipDialogTranscode">3</setting>
    <setting id="sslverify">true</setting>
    <setting id="startupDelay" default="true">0</setting>
    <setting id="syncDuringPlay">false</setting>
    <setting id="syncIndicator">999</setting>
    <setting id="SyncInstallRunDone" default="true">true</setting>
    <setting id="syncProgress">1</setting>
    <setting id="transcode_h265" default="true">false</setting>
    <setting id="transcodeHi10P" default="true">false</setting>
    <setting id="useDirectPaths">0</setting>
    <setting id="username">SiLeX</setting>
    <setting id="videoBitrate">20</setting>
</settings>
```

I had a couple of first-time-setup issues as well and if I remember correctly, it was very important to restart Kodi after adding the library. Also letting the addon start up for 10 seconds before trying any actions helps. The addon has options to completely reset the addon, and to add the databases from jellyfin to kodi. You must use this option to have the jellyfin librarys added to Kodi.

In the Jellyfin web ui admin interface Kodi must show as connected device as soon as the addon is enabled.

**Comment by CastagnaIT** [comment] 2020-10-11 15:20
> Not what you talk about this, I think exactly this happens already in Leia, when you delete a library folder. A popup asks if I want to remove the library data from this path.

the popup is not asked when running cleaning in background then kodi seem remove all by default

---

i have compared settings the only difference is this:

`<setting id="server">http://192.168.2.2:8096</setting>`

that in my settings server point to my local pc


tried again by deleting all user data files,
server notification dlna server:
![image](https://user-images.githubusercontent.com/3257156/95682292-bf9b3100-0be4-11eb-8d4b-89ef81ebf80e.png)

selected and set as addon mode,
at add libraries selection selected ALL,
now i can see the tvshow names when kodi scan library

i try navigate to tvshows kodi library:
is empty there are only these two links but broken
one point: smb:\\ another one: http:\\
![image](https://user-images.githubusercontent.com/3257156/95682497-cf674500-0be5-11eb-9e94-79bbe718fa47.png)

i try open jellyfin addon
![image](https://user-images.githubusercontent.com/3257156/95682369-24568b80-0be5-11eb-8f8d-0c527d872e07.png)
"Serie TV" folder library is added and should cointains my tvshows but if i try browse it:
show all subfolders:
![image](https://user-images.githubusercontent.com/3257156/95682414-5d8efb80-0be5-11eb-91ec-a74c17dd03eb.png)
but are all empty

**Comment by gersilex** [comment] 2020-10-11 15:27
Looks good and it is expected that those library folders are empty. The source is `smb://` for me, too, and it works.

Instead, the tvshows should appear "natively" in the Kodi librarys. You won't find them in the library folders. That's what I meant with "somehow Jellyfind adds those directly to Kodi, instead of creating STRM files".

![image](https://user-images.githubusercontent.com/2018039/95682675-dcd0ff00-0be6-11eb-9436-8d7f8442ae15.png)

Another way (without library integration) is to open the Jellyfin addon and browse from there. This must absolutely work to prove the Addon and your Jellyfin server work.

**Comment by CastagnaIT** [comment] 2020-10-11 15:47
do not know what missing are not able to make it work on kodi
works only through the web

**Comment by gersilex** [comment] 2020-10-12 00:04
I don't know what you're missing, either. It's so straight-forward I don't think you could miss anything. There is only one strange thing and that is that I have to leave and return to the home screen to see the changes.

I recorded me setting up a new Kodi instance (completely removed the user data folder, beforehand, of course). 

https://youtu.be/aNIKDQxUX5c

Maybe you find some differences. I also use the Jellyfin Kodi Addon on an Linux x86 PC with LibreElec without any issues regarding the Jellyfin addon installation.

**Comment by CastagnaIT** [comment] 2020-10-12 09:27
thanks your video help me
i have only changed http://jellyfin to http://192.168.2.2:8096
seem now working

casually i have discovered also a bad thing in jellyfin addon
that perform a direct access to Kodi database's
I don't know what it does because the code is too large to analyze
but this behaviour is not allowed by Kodi community rules, and this could explain the problems

the "files" are added in some way in the Kodi video library with a "plugin" path eg:
`plugin://plugin.video.jellyfin/7e0b1aa6c52d5c314547390ecd926b2a/?dbid=19&mode=play&id=c2658bb206be00b6d6814a0cad0b866f&filename=Legends.of.Tomorrow.4x03.Missione.Punk.ITA.ENG.1080p.mkv`

but i have not found the real source for these video library "files" added,
so i believe that these "files" items in the database without a source are rightly deleted when you perform the Clean library

**Comment by CastagnaIT** [comment] 2020-10-12 11:23
yes jellyfin manipulate the kodi database
found that in queries.py file there are all kodi tables
this is not suitable for regular operation of kodi

I will not waste time on addons that do not respect the rules of Kodi addons community

the only thing I can try to do is to try to propose a change in Kodi 19
to integrate library cleaning only to a specific folder (and so avoid clean all others paths)
that anyway I don't know if it will work, but i can try

so if jollyfin doesn't have problems on kodi 19 i can give it a try
for kodi 18 I will do nothing

**Comment by CastagnaIT** [comment] 2020-10-12 14:39
The change to Kodi 19 seem works good, the tvshow of jellifin are not removed in my first test

i can provide only a windows 64 build of Kodi
Kodi 19 Patched: https://www.dropbox.com/s/5j4u1uvvmcap5dm/LibClean_Kodi19_Patched_Win64.zip?dl=0
You can overwrite the kodi installation folder content with the zip or if you prefer can be used as portable mode
(launch the executable with `-p` parameter)

This is the nf addon patched to works with the patched kodi build:
[LibClean_plugin.video.netflix_1.10.0+matrix.1_20201012.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5365730/LibClean_plugin.video.netflix_1.10.0%2Bmatrix.1_20201012.zip)

a feedback is welcome
please also check if the nf tvshow's are correctly removed after the sync (try remove a title)

**Comment by gersilex** [comment] 2020-10-12 20:11
Thanks for the updates. I absolutely understand and respect your decision on not adding workarounds for other addons not following the rules. We already have proven that there is no issue with the Netflix addon because it also happens on Kodi's built-in Library Cleanup function. 

Do you think it would make sense to add an additional option to your Netflix addon to just skip triggering the Cleanup so we can consult with the Jellyfin team to improve the Library handling and follow the rules? This would get us Jellyfin+Netflix users going again for the time being. Would this be an acceptable workload for you and do you think this fits into the style of your addon? If so, we would be very happy to have it.

Regarding the patched win64 build of Kodi. I'd love to test this for you but I am struggling to run Jellyfin there, because it tries to use a non-exstisting constant called `xbmc.LOGNOTICE`.

```                                                     File "C:\Users\silex.WINDADDY\Downloads\LibClean_Kodi19_Patched_Win64\Kodi19_Patched\portable_data\addons\plugin.video.jellyfin\jellyfin_kodi\helper\loghandler.py", line 64, in emit
                                                       xbmc.log(string, level=xbmc.LOGNOTICE)
                                                   AttributeError: module 'kodi_six.xbmc' has no attribute 'LOGNOTICE'
```

I don't want to bother you even more with Jellyfin stuff. Instead I'll figure out a way to test the libclean variant of your Netflix addon without Jellyfin.

**Comment by gersilex** [comment] 2020-10-12 21:22
Here are the results:

Environment: Your Kodi19 win64 patched build and patched netflix addon + source folder with movies over CIFS/SMB

I can confirm that running the Sync in Netflix only removes the STRM files/folder I deleted from the Kodi library and does NOT touch the other database entries from the SMB source I removed before syncing.

Thanks also for the heads-up with running Kodi in portable mode. Didn't know that flag existed.

**Comment by CastagnaIT** [comment] 2020-10-13 06:12
yes i have forgot to add the fixed version for kodi 19:
[plugin.video.jellyfin_fixed_kodi19.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5369296/plugin.video.jellyfin_fixed_kodi19.zip)

**Comment by CastagnaIT** [comment] 2020-10-13 11:46
the patch for Kodi 19 has been accepted,
so i will be able to modify the addon to clean the kodi library only in the specific netflix folder
and so avoid the problems with jellyfin and similar addons

**Comment by CastagnaIT** [comment] 2020-10-24 07:54
Fixed by adding "Clean library by directory" to new Kodi 19 add-on release

**Closed by CastagnaIT** 2020-10-24 07:54 UTC
