### ISSUE TITLE
KeyError: 81277950

### ISSUE THREAD

**Issue by bypper** [CastagnaIT/plugin.video.netflix#891] opened 2020-10-11 18:42 UTC
#### Your Environment
- Netflix add-on version: 1.10.0
- Operating system version/name: LibreElec 9.0.2
- Device model:  Odroid C-2

### Describe the bug
Suddenly, when playing some film, Kodi show an error dialog with the following text (spanish):
"**Error del complemento Netflix**

_El complemento encontro el siguiente error:
KeyError: u'81277950
Los detalles del error se han escrito en el archivo de registro de Kodi. Si el mensaje de error no proporciona orientación sobre como resolver el problema o si continua recibiendo este error, informelo en Github siguiendo las instrucciones del archivo Leame_"

English translate:
_**Netflix addon error**
Addon found the following error:
KeyError: u'81277950
Error details are written in Kodi record file. If error message not help for solve the problem or if you keep getting this error, report in Github following Readme file instructions_"

When I click in the "Accept" button, dialog dissapear, but a few minutes later, it show again, and again, and again...
Dialog box may appear even if you're not inside Netflix addon.

#### Expected behavior
Dialog box should not appear.

#### Actual behavior
Description above.

#### Steps to reproduce the behavior
I cannot reproduce whenever I want, it occurs apparently randomly.

#### Possible fix
Error can show in log, but I think it not must show suddenly in the middle of reproduction.

### Debug log
```
2020-10-11 17:13:50.697 T:3712058224   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/events_handler.py", line 154, in fallback_event_video_queue self.add_event_to_queue(data['event_type'], data['event_data'], data['player_state'])                                                                                                        
     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/events_handler.py", line 166, in add_event_to_queue  manifest = get_manifest(videoid)
     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/events_handler.py", line 258, in get_manifest return G.CACHE.get(CACHE_MANIFESTS, cache_identifier)
     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/cache.py", line 39, in get data = self._make_call('get', call_args)
     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/cache.py", line 97, in _make_call_service return getattr(G.CACHE_MANAGEMENT, callname)(**params)
     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/cache/cache_management.py", line 146, in get raise_from(CacheMiss, exc)
     File "/storage/.kodi/addons/script.module.future/libs/future/utils/__init__.py", line 456, in raise_from raise e
     CacheMiss
```

**Comment by CastagnaIT** [comment] 2020-10-12 06:37
> I cannot reproduce whenever I want, it occurs apparently randomly.

usually there are precise steps to reproduce the problem, try to find it

> Error can show in log, but I think it not must show suddenly in the middle of reproduction

here you talk about of middle playback of netflix video content or non-netflix video content?
before you have said:

> Dialog box may appear even if you're not inside Netflix addon

> Error can show in log

if you do not provide a complete log as widely requested in the readme/issue instructions this thread will not be accepted

**Comment by bypper** [comment] 2020-10-12 07:57
> > I cannot reproduce whenever I want, it occurs apparently randomly.
> 
> usually there are precise steps to reproduce the problem, try to find it

If I don't know these steps, I can't make them up. I see them, all times when I come in the Addon.
Sorry, I cannot tell you anymore about this.

> here you talk about of middle playback of netflix video content or non-netflix video content?
> before you have said:
> 
> > Dialog box may appear even if you're not inside Netflix addon

Yes, when Dialog error starts to appear, it still appears every few minutes, even if I exit the Addon, and I go to another place or I'm viewing local content...

> > Error can show in log
> 
> if you do not provide a complete log as widely requested in the readme/issue instructions this thread will not be accepted

Do you want me to attach the full Kodi log to you? with all the unrelated activity? for how long?

**Comment by CastagnaIT** [comment] 2020-10-12 08:00
> Do you want me to attach the full Kodi log to you? with all the unrelated activity? for how long?

Yes full debug log, how to do here:
https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

**Comment by CastagnaIT** [comment] 2020-10-17 09:04
Do you think to attach the full debug log?
without it i will close this issue
because there is not enough information to identify your problem

**Comment by bypper** [comment] 2020-10-17 11:18
Hi,
Log is here:
https://paste.kodi.tv/ayunejases.kodi

Regards,

**Comment by CastagnaIT** [comment] 2020-10-17 14:24
you have not follow instructions to get a debug log
this have no useful info

**Comment by bypper** [comment] 2020-10-17 14:47
And now...
http://casa.dyn.bersol.info:10481/kodi.log

kodi.log service not accept wide content.

**Comment by CastagnaIT** [comment] 2020-10-17 15:22
better but i not have full debug info, because the addon is not set as debug

> [plugin.video.netflix (11)] The debug logging level is set as "Info"

anyway, i noticed something of strange, so in very short space of time is called the addon to play a file many times, and also from different instances:

2020-10-17 16:35:13.665 T:3384877936    INFO: [plugin.video.netflix (9)] Playing episode_80107404
2020-10-17 16:35:17.552 T:2958099312    INFO: [plugin.video.netflix (10)] Playing episode_80107403
2020-10-17 16:35:17.884 T:3557839728    INFO: [plugin.video.netflix (11)] Playing episode_80107403
only at this point seem kodi start load the video, but there is another call after
2020-10-17 16:35:37.803 T:3557839728    INFO: [plugin.video.netflix (11)] Playing episode_80107403
all this definitely causes addon problems

the first call have also a customized call path:
`/play/show/80014749/season/80032360/episode/80107403/extrafanart/`

`/extrafanart/` not concern this addon, this could means that this path is called by external things

that make me thing that you are using a particular skin that not works as it should and cause all this problems
what is the name of the skin you use?

try set "Estuary" Kodi skin and try again

**Comment by bypper** [comment] 2020-10-17 16:26
Yes, I have changed skin (Black GlassNova) and I don't get error.
It hurts, this skin likes me so much, but problem looks solved.

Thank you so much CastagnaIT,
Best Regards,

**Closed** 2020-10-17 20:16 UTC

**Comment by CastagnaIT** [comment] 2020-10-18 07:45
Please try update with this pathed version:
[plugin.video.netflix_1.10.0_20201018_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5397184/plugin.video.netflix_1.10.0_20201018_t1.zip)

let me know if could resolve the problem with the Black GlassNova skin

**Comment by bypper** [comment] 2020-10-19 10:02
Hi CastagnaIT,
Yes, with patched version, error is not showed already.
Great Job!

But, there is a little problem...
Addon cannot update status seen, when Episode end. It show an error.

I attach last log:
[http://casa.dyn.bersol.info:10481/kodi.log](http://casa.dyn.bersol.info:10481/kodi.log)

Best Regards,
Alberto
