### ISSUE TITLE
 No title or thumbnail - Netflix and Upnext

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#105] opened 2019-06-14 09:43 UTC
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information
I am not really sure if the problem concerns the Netflix add-in or the UpNext add-on, but it seems to me that the problem is caused by the Netflix addition of all parameters to UpNext . Just in case, I will inform you in both places. 
### Addon version used

last master from git

### Description
When playing some shows such as The Ranch, the Notification window from the UpNext add-in does not receive either a thumbnail or the correct title (as in the screenshot). On other series that I checked works without any problems.
The playback of the next title itself works.
I attach the logs on the original skin.
Versions of UpNext and Netflix addons - last master fromgit

### Steps to Reproduce

1. Run The Ranch - any episode
2. scroll to end

**Expected behavior:** [What you expected to happen]

Visible thumbnails and title

**Actual behavior:** [What actually happened]
Not visible thumbnails and title
## Context (Environment)

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

## Debug log

https://pastebin.pl/view/d81feef3

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment] 2019-06-15 09:00
I checked it was caused by the TV series that still do not have a rating
now fixed

**Closed by CastagnaIT** 2019-06-15 09:00 UTC

**Comment by notoco** [comment] 2019-06-15 14:49
No jesteś wielki, chłopie!
You are great, man!
