### ISSUE TITLE
Titles without czech subtitles appear non-existent

### ISSUE THREAD

**Issue by Tajnymag** [CastagnaIT/plugin.video.netflix#1198] opened 2021-07-03 08:31 UTC
#### Your Environment
- Netflix add-on version: 1.16.1+matrix.1
- Operating system version/name: LibreELEC 9.95.4 10.0
- Device model:  Intel NUC (highly probably doesn't matter)

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Shows and movies which do not have czech subtitles are not present in the Kodi addon. They can be found and played in a browser and android app without any problem. No VPN used, thus the titles are probably legally available in the region.

This also applies to specific show episodes/seasons. Derry Girls (2018) only lists the second season in Kodi but I can watch both seasons in the browser/app. As you guessed it, first season doesn't have czech subtitles and the second does.

I don't think this is something coming from Kodi itself, as I have many local titles without subtitles.

I haven't yet found whether this applies also applies to titles with czech dubbing and subtitles missing (whether a czech movie without czech subtitles would show up). All the titles that I've found, which had a czech audio track, also had czech subtitles.

#### Expected behavior

All titles available in the browser and app should be available in the addon.

#### Actual behavior

Only titles with czech (?perhaps "localized"?) subtitles are available.

#### Steps to reproduce the behavior

1. set Netflix locale to czech language
2. be in czech region (can't test outside it)
3. try to search for a non-localized movie or a show (Now You See Me 2 for example)

#### Possible fix

Can't really say. 

### Debug log

The debug log can be found here:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6758086/kodi.log)

#### Other information

Sorry for not giving more information right out of the bat. I am prepared to cooperate and log/post/try any suggestions.

#### Screenshots

![My List in Kodi](https://user-images.githubusercontent.com/3985946/124348307-8d55b780-dbe9-11eb-818d-f6f092cb8c0d.png)
![My List in browser](https://user-images.githubusercontent.com/3985946/124348311-8fb81180-dbe9-11eb-86d2-ea7976e2181f.png)

**Comment by Tajnymag** [comment] 2021-07-04 07:37
UPDATE: After setting the Netflix user's locale to english (through browser), all titles are suddenly foundable in the addon. Thus for reproduction, I guess it would suffice to change your Netflix locale to czech language and not bother with region or kodi locale.

**Comment by Tajnymag** [comment] 2021-07-04 11:01
Might be related to https://github.com/CastagnaIT/plugin.video.netflix/issues/1044. Compared to https://github.com/CastagnaIT/plugin.video.netflix/issues/1044, I can prove it isn't tied to any region switching and should be in theory reproducable outside of my country.

**Comment by CastagnaIT** [comment] 2021-07-04 13:32
are you really sure that in your kodi skin not have some filter set in the sidebar?

**Comment by Tajnymag** [comment] 2021-07-04 13:33
Yes, I am sure. It doesn't happen with local content and I can show/hide the content by changing the locale of Netflix through their web interface.

**Comment by CastagnaIT** [comment] 2021-07-04 13:36
please provide a screenshot of the skin sidebar while you are within "My List" menu
i want make sure, because all report of this type in the past was for skin problems

**Comment by Tajnymag** [comment] 2021-07-04 13:41
![screenshot00001](https://user-images.githubusercontent.com/3985946/124387289-38e03400-dcde-11eb-9430-474bb3e6b664.png)

**Comment by CastagnaIT** [comment] 2021-07-04 13:46
thanks, can you try this
exit from addon, go to in addon expert setting
and select Clean cache on disk and memory
then try see My list if works

**Comment by Tajnymag** [comment] 2021-07-04 13:52
Cache deleted:
![screenshot00004](https://user-images.githubusercontent.com/3985946/124387582-75605f80-dcdf-11eb-9827-d732c710eb76.png)

Still the same:
![screenshot00005](https://user-images.githubusercontent.com/3985946/124387585-772a2300-dcdf-11eb-9f7f-4c40a002b453.png)

Logs:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6759974/kodi.log)

**Comment by CastagnaIT** [comment] 2021-07-04 14:28
thanks screenshots are no more needed
but this is not due to czech subtitles, the query is done by requesting the My list directly without any filter

please update the addon with this
[plugin.video.netflix_1.16.1+matrix.1_20210704_dbg.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6760022/plugin.video.netflix_1.16.1%2Bmatrix.1_20210704_dbg.zip)

open again My list and attach a new log here
this will provide me the raw data to see

**Comment by Tajnymag** [comment] 2021-07-04 16:53
Sorry for the delay. Here it is:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6760269/kodi.log)

**Comment by CastagnaIT** [comment] 2021-07-05 16:12
Please let me know if with this test in mylist now you can see all titles:
[plugin.video.netflix_1.16.1+matrix.1_20210705_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6765425/plugin.video.netflix_1.16.1%2Bmatrix.1_20210705_t1.zip)

WARNING please do not use this test version to edit your my list because is not done and will cause problems

**Comment by Tajnymag** [comment] 2021-07-05 16:30
Unfortunately, the problem still persists even with the 20210705 version of the plugin. I've updated the addon, cleared cache, restarted the system and once I get to My List, the list still only contains 4 out of 7 titles.

Recorded a log:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6765480/kodi.log)

**Comment by CastagnaIT** [comment] 2021-07-05 17:52
Then the problem is not even on the type of query made
Is the first time that you use this addon?
Have you tried logging out/relogin?
The type of internet connection is different from the Kodi device and where you use the webbrowser?
Your internet connection come from like smartphone or internet wifi sim-box?

**Comment by Tajnymag** [comment] 2021-07-05 17:58
First time: Not really. Have been using it for at least a year. This problem goes back to Leia.

Relogin: Not in the 20210705 version.

Connection: Yes. The same WiFi network. Not the same device.

**Comment by Tajnymag** [comment] 2021-07-05 18:11
1) Tried relogging. Netflix didn't like my requests, so I had to login using an authentication key. No difference.

2) [NFSystemInfo.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/6765831/NFSystemInfo.txt)

**Comment by CastagnaIT** [comment] 2021-07-05 18:47
can you show me how you set the czech locale with a browser screenshot?
i have these:
![immagine](https://user-images.githubusercontent.com/3257156/124509266-ee3fe400-ddd1-11eb-8d0c-29a3624b1ade.png)

**Comment by Tajnymag** [comment] 2021-07-05 18:50
"Čeština"
![obrazek](https://user-images.githubusercontent.com/3985946/124509607-981f7080-ddd2-11eb-90af-01d3ecf8308a.png)

**Comment by Tajnymag** [comment] 2021-07-05 19:04
I've just installed Kodi on Arch Linux with "plugin.video.netflix_1.16.1+matrix.1_20210705_t1.zip" and can confirm the issue is present here too. No other addon, clean Kodi installation.

As soon as I set in the browser user's locale to English or Espaňol, the titles show up.

**Comment by CastagnaIT** [comment] 2021-07-05 19:27
i have tried on my station but i cannot replicate your problem
I have no other ideas on how to solve this situation
because I don't have any other parameters to my knowledge that can influence this problem

I can let you try this experimental version:
[plugin.video.netflix-http2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6765994/plugin.video.netflix-http2.zip)
here use login with user+password (with this exp. is working), please do not use the auth key

**Comment by Tajnymag** [comment] 2021-07-05 19:38
OK, I'll try to study the problem more. Should we close the issue then?

I've installed the http2 version, but I can't login through the email+password method. The credentials are correct (sign-in through Chrome works) but I still get the "incorrect password" message. I'll try again later in the week, hoping Netflix unflags the IP.

**Comment by CastagnaIT** [comment] 2021-07-05 19:42
This is strange in the exp version the normal login was working at least until last days
No need to close the issue, other users could write

**Comment by Liqianyu** [comment] 2021-07-15 19:15
Have tried https://www.netflix.com/DoNotTest ?
Is it possible that this is an A/B test.

**Comment by Tajnymag** [comment] 2021-07-15 19:51
> Have tried https://www.netflix.com/DoNotTest ?
> Is it possible that this is an A/B test.

I haven't. I've turned off the testing right now, but I can't test the result until Saturday.

**Comment by CastagnaIT** [comment] 2021-10-06 12:20
no other reports from other users after months,
I am closing this issue as it is not solvable

**Closed by CastagnaIT** 2021-10-06 12:20 UTC
Labels: Resolution: Not reproducible
