### ISSUE TITLE
Error message after playback stops: AMPlayback disabled due to exception: u'percentage'

### ISSUE THREAD

**Issue by lameventanas** [CastagnaIT/plugin.video.netflix#1066] opened 2021-02-08 15:53 UTC
#### Your Environment
- Netflix add-on version: 1.12.2
- Operating system version/name: Linux
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

After playing any Netflix video, I get an error message on the screen, saying: AMPlayback disabled due to exception: u'percentage'

#### Steps to reproduce the behavior

1. Export a tv show
2. Play an episode, let it finish

### Debug log

The debug log can be found here:

https://paste.kodi.tv/raw/jarefohobe

**Comment by CastagnaIT** [comment] 2021-02-08 16:37
your log is not acceptable
attach a new log by following instruction steps on GitHub Readme

**Comment by jakermx** [comment] 2021-02-09 01:06
I have seem this error just 1 or 2 times, since asciidisco version...Since this version is MT and run(I would said depends on) in paralell with the Syste Video Player....there could be some little times that when the tick time  is les than a minute and the Player triggers 2 events at the same period of event handling...

**Comment by CastagnaIT** [comment] 2021-02-14 16:51
if no log will be provided this issue will be closed on the next days

**Comment by lameventanas** [comment] 2021-02-15 07:00
Sorry, I've been busy so I couldn't take the time to do this.
One thing I noticed is that this error happened when watching a tv show called "Troy: Fall of a City", but didn't happen with others.
I also found a more annoying bug in which after watching a tv show, it's not just marked as watched, but it disappears from the library completely, so I will take both logs.

**Comment by CastagnaIT** [comment] 2021-02-15 07:51
> I also found a more annoying bug in which after watching a tv show, it's not just marked as watched, but it disappears from the library completely, so I will take both logs.

This problem will not considered, because Kodi 18 library has some bug, i suggest you in near future to use the new Kodi 19.x

**Comment by lameventanas** [comment] 2021-02-19 12:14
I updated to Kodi 19.0RC1, I built it from source.
Now I get this message whenever I play any video in Netflix, at the beginning:
`AMStreamContiniuity disabled due to exception: 'isdefault'`

Ino longer getting the exception I described in my first post, at the end of playback, but the file I played still disappears from the library.

I enabled debug in `advancedsettings.xml` [here](https://paste.kodi.tv/upehepiser.kodi) is the result.

The actions I took for this log:
Started Kodi, Opened Netflix, played an episode of "Troy: Fall of a City", and got the exception at the beginning.

1. Started Kodi
2. Opened the Netflix addon
3. Opened the exported library
4. Selected "Troy: Fall of a City"
5. Selected episode 4
6. I got the message: `AMStreamContiniuity disabled due to exception: 'isdefault'`
7. I seek close end, let it play until it finishes
8. I don't get the same exception as described in my first post, but the episode I just played is gone from the library

**Comment by CastagnaIT** [comment] 2021-02-20 13:19
You have incontered this error due to the Kodi migration (19 over 18 ver)
it is usually not recommended to make this migration due to heavy changes of this new Kodi version, it was better install it from scratch

anyway i have managed this problem, in order to fix `AMStreamContiniuity disabled due to exception: 'isdefault'` error
update the add-on with this fix: [plugin.video.netflix_1.13.1+matrix.1_20210220_fix.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6015026/plugin.video.netflix_1.13.1%2Bmatrix.1_20210220_fix.zip)

Then after opened add-on Expert settings, select "Clear in-memory and on-disk cache"

**Comment by lameventanas** [comment] 2021-02-22 04:47
Thanks a lot for fixing this!
I noticed a new release of version v1.14.0+matrix.1, I installed it and it works well now.
At the beginning I was getting a message saying something like "Netflix features disabled" at playback start, which disabled subtitles and other things, but somehow I did something that made it go away, can't remember what.

Also, that library "bug" that I described before where videos disappeared from the library after playback was due to having the "Hide watched" option enabled. Really embarrassing, sorry about that. At least it gave me the motivation to build Kodi 19.

I was looking on the sidebar for an option to sort my exported list alphabetically.
It's always sorted by Date, and it's disabled so I can't change it.
![image](https://user-images.githubusercontent.com/11934069/108663408-d8f9a580-7513-11eb-9a20-5c5952f09e9a.png)
I can't find this in the settings either, everything there is et to sort alphabetically.
Is there any way to sort this alphabetically?

**Comment by CastagnaIT** [comment] 2021-02-22 09:31
> I was looking on the sidebar for an option to sort my exported list alphabetically.
> It's always sorted by Date, and it's disabled so I can't change it.

this is not a bug, not all lists can be sorted by skin options, this depends by each add-on features,
in this case, for some lists, you can change the sort order from add-on `Main menu items` settings

> At the beginning I was getting a message saying something like "Netflix features disabled" at playback start,

This can happen when you play a video from Kodi library or widgets,
happen due to Kodi 19 bug not resolved by Kodi developers

**Comment by CastagnaIT** [comment] 2021-03-15 17:23
> AMPlayback disabled due to exception: u'percentage'

i am not able to reproduce the reported bug,
now the project is focused on Kodi 19,
if the error comes back on Kodi 19 open a new Issue

**Closed by CastagnaIT** 2021-03-15 17:23 UTC
Labels: Resolution: Not reproducible

**Comment by Havishjupudi** [comment] 2024-04-21 14:52
Hey I got same error first time when I downloaded Netflix in v21 it worked flawlessly and again I installed the v20 for some idiotic reason that I don't even know it gives the error.
Error : AMPlayback disabled due to exception: u'percentage'
Any help pls.. and also I'm new to kodi so I don't much about this application.
