### ISSUE TITLE
RPi 3: Playback suddenly doesn't work anymore

### ISSUE THREAD

**Issue by DerGanjalf** [CastagnaIT/plugin.video.netflix#1300] opened 2022-02-02 14:45 UTC
#### Your Environment
- Netflix add-on version: 1.12.8-Leia
- Operating system version/name: Libreelec 9.2.8
- Device model:  Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
I cannot start the playback and only receive an MSL error. Two days ago everything worked as expected, during this period no changes were made on the client. I have another Raspberry Pi 3 which is set up exactly the same way and has the same issue. This problem does not only occur on my clients. As stated in: https://github.com/CastagnaIT/plugin.video.netflix/discussions/1299, one other user has the same problem in the same period of time.

#### Expected behavior
The playback should start, no MSL error should occur.

#### Actual behavior
Playback does not start, MSL error message pops up.

#### Steps to reproduce the behavior
1. Run the plugin on Raspberry Pi and Kodi 18 (according to the discussion, the exact Kodi version doesn't seem to matter)
2. Login to Netflix account
3. Start playback of a show or movie

#### Possible fix
Reinstalling Widevine through InputStream Helper did not work, neither did reinstalling the whole addon and clearing the addons' cache in it's settings. Maybe the problem is caused by change on Netflix' side

### Debug log
The debug log can be found here:
http://ix.io/3OqN

#### Other information
https://github.com/CastagnaIT/plugin.video.netflix/discussions/1299

**Comment by xmiklos** [comment] 2022-02-02 15:18
Same issue here (Raspberry Pi 3 + Libreelec). Yesterday it was working. Today can't play anything on netflix and getting same error msg as reported. I tried reinstalling widevine/netflix addon, clearing cache, logging out. Issue persists.

Thx.

**Comment by helviojr** [comment] 2022-02-02 16:36
Same here. Windows 10, Leia 18.9, Netflix 1.12.8. FAQ steps followed, no luck. Any video. Widevine seems to be OK, as other add-ons that also use it continues to work correctly.

**Comment by tommikokko** [comment] 2022-02-02 17:32
Same here, but with Raspberry Pi 4. Worked two days ago, yesterday did not.

**Comment by krom54** [comment] 2022-02-02 17:47
Same here in France kodi 18 and updated plugin, impossible to launch anything.

Error message:

```
MSLerror: this title is not available in instant access. 
please select another one. 
```

in french :

```
MSLerror: ce titre n'est pas disponible en accès instantané. 
veuillez en sélectionner un autre. 
```

Maybe Netflix locks the playback to third party applications ???

**Comment by dranidis** [comment] 2022-02-02 19:46
Same here with Raspberry Pi 3 and KODI Libreelec. I noticed the problem yesterday night and tried Logout/Login, RESET ESN, clear Cache. Not solved.

**Comment by jba31** [comment] 2022-02-02 20:04
Hi,
Same error on raspberry pie 3 with osmc

**Comment by emc02** [comment] 2022-02-02 20:19
Same here on RPi4, LE9.2.8

**Comment by Martinius** [comment] 2022-02-02 20:22
+1 RPi4 Kodi 18 on Rasperian

**Comment by sdfrir** [comment] 2022-02-02 20:24
Hi
i have same issue.
raspberry 4 raspbian headless made to work with kodi and netflix. 

Siencerly 
S

**Comment by sdfrir** [comment] 2022-02-02 20:25
* also tried the instructions to no avail.

**Comment by karthanistyr** [comment] 2022-02-02 20:26
An update on the kodi forums: https://forum.kodi.tv/showthread.php?tid=329767&pid=3084615#pid3084615

**Comment by jba31** [comment] 2022-02-02 20:27
I fix it after read discussions (on osmc/rasp3)

/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py

--- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
+++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
@@ -182,7 +182,7 @@

         params = {
             'type': 'standard',
-            'viewableId': [viewable_id],
+            'viewableId': viewable_id,
             'profiles': profiles,
             'flavor': 'PRE_FETCH',
             'drmType': 'widevine',

**Comment by emc02** [comment] 2022-02-02 20:45
> I fix it after read discussions (on osmc/rasp3)
> 
> /home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
> 
> ```
> 
> --- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
> +++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
> @@ -182,7 +182,7 @@
> 
>          params = {
>              'type': 'standard',
> -            'viewableId': [viewable_id],
> +            'viewableId': viewable_id,
>              'profiles': profiles,
>              'flavor': 'PRE_FETCH',
>              'drmType': 'widevine',
> ```

Can confirm it works!!! Thanks!

**Comment by krom54** [comment] 2022-02-02 21:19
yep this workaround work fine 

just add` 'viewableId': viewable_id,`  below `'viewableId': [viewable_id],` in `/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py` 

thx a lot .

**Comment by dreia2k** [comment] 2022-02-02 22:53
I am encountering the same error on OSMC / Kodi 19 / rPi 4.
Netflix addon and Kodi are up to date.

There is no directory `/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/` for me though.

The only `msl_handler.py` file I have got is `/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py`.
When trying the workaround on this one nothing changes and the error still occurs.
Also tried rebooting...

Does anyone know why my addon is missing files?

**Comment by JoshOrndorff** [comment] 2022-02-03 00:49
@dreia2k I'm using LibreElec on Raspberry Pi 4, and I also don't have the exact file path others are mentioning. It seems like you made a typo in your comment though, because you then went on to say that you do have a file at the same path. Could clarify where you did find a similarly named file? Did you try rebooting the device and other basic steps after making the change?

Does anyone else have any tips to solve what seems to be the same error on libreelec?

**Comment by CeEs-atd** [comment] 2022-02-03 06:56
With OrangePi PC and LE10 nightly20210807 (Kodi Matrix 19.1) acutal addons and WV 4.10.2252.5, MSL=1 selected in the NF addon I also have no playback and the workararound can not be applied (see [JoshOrndorff](https://github.com/JoshOrndorff)'s post above)
_BUT_ changing to MSL=default in the addon partially works: all NF content can be seen with SD resolution

With RPi3b+ and LE11 nightly 20220107, (Kodi Leia 20.0-ALPHA1), and WV 4.0.2254.5, MSL=1: Everything is fine with Netflix HD playback.

**Comment by tarifari** [comment] 2022-02-03 10:55
> I fix it after read discussions (on osmc/rasp3)
> 
> /home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
> 
> ```
> 
> --- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
> +++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
> @@ -182,7 +182,7 @@
> 
>          params = {
>              'type': 'standard',
> -            'viewableId': [viewable_id],
> +            'viewableId': viewable_id,
>              'profiles': profiles,
>              'flavor': 'PRE_FETCH',
>              'drmType': 'widevine',
> ```

nice, this also works for me.

**Comment by DerGanjalf** [comment] 2022-02-03 11:39
I can confirm that the workaround fixes the problem. Is it possible to integrate this in the plugin's code, or is it just a temporary fix?

**Comment by krom54** [comment] 2022-02-03 13:12
> But now the extensions won't open, and kodi passes on a python error that it can't import the module I modified.

`'viewableId': [kwargs[viewable_id]], ` seems to me more accurate , be sure to respect indentation .

**Comment by Taijian** [comment] 2022-02-03 17:20
> I made what I expected to be the corresponding change:
> 
> ```diff
> -     'viewableId': [kwargs['viewable_id']],
> +     'viewableId': kwargs['viewable_id'],
> ```
> 
> But now the extensions won't open, and kodi passes on a python error that it can't import the module I modified.

Have you tried rebooting your device in the meantime? Because I did exactly this on my machine (CoreElec Matrix) and it fixed the issue just fine!

**Comment by redstorm1** [comment] 2022-02-03 18:59
> I fix it after read discussions (on osmc/rasp3)
> 
> /home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
> 
> ```
> 
> --- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
> +++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
> @@ -182,7 +182,7 @@
> 
>          params = {
>              'type': 'standard',
> -            'viewableId': [viewable_id],
> +            'viewableId': viewable_id,
>              'profiles': profiles,
>              'flavor': 'PRE_FETCH',
>              'drmType': 'widevine',
> ```

Fixed on CoreElec 9.27 Kodi 18 Leia , after the edit restart Kodi. Thanks for the find...

**Comment by sdfrir** [comment] 2022-02-03 19:00
It works :) thank you 

raspian headless kodi

**Comment by helviojr** [comment] 2022-02-03 22:02
Confirmed: Windows 10, Leia 18.9, plugin.video.netflix 1.12.8: fix on msl_handler.py works!! So it is not a hardware-dependant problem. The commit above should be applied (probably some change in Netflix interface).

**Comment by JoshTheTofu** [comment] 2022-02-03 22:55
Hi guys

I am using Kodi 18.9 on A Rpi3 and I can't for the life of me find the .kodi hidden file. How do I show the hidden files in LibreElec?

Thanks in advance

Kind regards

Josh

**Comment by Tudwall** [comment] 2022-02-04 01:39
> I fix it after read discussions (on osmc/rasp3)
> 
> /home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
> 
> ```
> 
> --- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
> +++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
> @@ -182,7 +182,7 @@
> 
>          params = {
>              'type': 'standard',
> -            'viewableId': [viewable_id],
> +            'viewableId': viewable_id,
>              'profiles': profiles,
>              'flavor': 'PRE_FETCH',
>              'drmType': 'widevine',
> ```

I applied this fix and it worked! Thank you so much!

**Comment by tarifari** [comment] 2022-02-04 10:10
> Hi guys
> 
> I am using Kodi 18.9 on A Rpi3 and I can't for the life of me find the .kodi hidden file. How do I show the hidden files in LibreElec?
> 
> Thanks in advance
> 
> Kind regards
> 
> Josh

how do you want to access it? just type the directory in.

**Comment by sdfrir** [comment] 2022-02-04 16:06
> 

Hi, 
this is basic stuff. but everyone need to learn someday :)

log in using SSH or use terminal if you have GUI (Desktop) 
and using command called "cd" go to "/" this is like Windows "C:" directory so type in your terminal "cd /".
then using another command type "ls" this command will show you content of directory in which you currently are in this case the "/" directory. 

look for "home" directory and to go into this directory type in terminal "cd /home" then again use "ls" command to show you content of this directory and there should be your username. in my case is "pi" because this is basic username in "raspbian" OS.

so now hop into your username directory using "cd /home/Your username" or in my case "cd /home/pi" 

and now your main problem this directory is hidden because it has dot in as first letter so to see hidden folders and files type in "ls -a" 

now again type "cd /home/your username/.kodi/
do "ls" for the practice :)
so now when we know where the kodi is installed type in 
"cd /home/YOUR USERNAME/.kodi/addons/plugin.video.netflix/resources/lib/services/msl" 
remember you must type in your username which you have found looking in your home directory

then do again "ls" command and there should be our problem file :) called "msl_handler.py"
now use build in old but trusty nano text editor, type in your command line 
"nano msl_handler.py" 

and remember when modifying code DO NOT accidentally type any letter or number because this can crash your netflix.
and now using your arrow keys navigate to part which will look like this 

params = {
             'type': 'standard',
            'viewableId': [viewable_id],
             'profiles': profiles,
             'flavor': 'PRE_FETCH',
             'drmType': 'widevine',

what you want to do is add new like which solves this problem make new line UNDER "'viewableId': [viewable_id],"

         params = {
             'type': 'standard',
            'viewableId': [viewable_id],
            **'viewableId': viewable_id,**
             'profiles': profiles,
             'flavor': 'PRE_FETCH',
             'drmType': 'widevine',

and now using key combination CTRL + S first save this file and using another combination CTRL + X exit editor 
type in your terminal "reboot" which will restart your device and will kick you out of SSH,
after this your netflix should work perfectly as it did 

if you need more help just write me a message 

Sincerly S

**Comment by CastagnaIT** [comment] 2022-02-04 16:36
i need someone with Kodi 18 + RPI update with this test:
[plugin.video.netflix_1.12.8_20220204_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8004685/plugin.video.netflix_1.12.8_20220204_t1.zip)

and let me know if from the first time that you run a video (declared 1080p) will be run at 1080p (see video info or video settings when in playback)

**Comment by JoshTheTofu** [comment] 2022-02-04 18:30
@sdfrir 

Thank-you so much for your help, you helped me understand my issue and it is all working now. 

After the reboot it wouldn't play at all, so I kept going over your instructions, it turned out it was a separate issue with an incompatible WideVine version. 

Your instructions are so good they should be in the Wiki.

Cheers

Josh

**Comment by jaykijay** [comment] 2022-02-04 19:29
> i need someone with Kodi 18 + RPI update with this test: [plugin.video.netflix_1.12.8_20220204_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8004685/plugin.video.netflix_1.12.8_20220204_t1.zip)
> 
> and let me know if from the first time that you run a video (declared 1080p) will be run at 1080p (see video info or video settings when in playback)

Works fine here,
1080P (VP9) works, too

**Comment by DerGanjalf** [comment] 2022-02-04 19:32
@CastagnaIT I can also confirm this works. Debug Log, if needed: http://ix.io/3OFF

**Comment by xelld** [comment] 2022-02-04 22:07
> > I fix it after read discussions (on osmc/rasp3)
> > /home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
> > ```
> > 
> > --- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
> > +++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
> > @@ -182,7 +182,7 @@
> > 
> >          params = {
> >              'type': 'standard',
> > -            'viewableId': [viewable_id],
> > +            'viewableId': viewable_id,
> >              'profiles': profiles,
> >              'flavor': 'PRE_FETCH',
> >              'drmType': 'widevine',
> > ```
> 
> I applied this fix and it worked! Thank you so much!

I can confirm it works, thanks.

**Comment by EatonEmmerich** [comment] 2022-02-05 16:40
Can confirm the 

> I fix it after read discussions (on osmc/rasp3)
> 
> /home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
> 
> ```
> 
> --- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
> +++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
> @@ -182,7 +182,7 @@
> 
>          params = {
>              'type': 'standard',
> -            'viewableId': [viewable_id],
> +            'viewableId': viewable_id,
>              'profiles': profiles,
>              'flavor': 'PRE_FETCH',
>              'drmType': 'widevine',
> ```

After making this quick patch, it's now working on Libreelec x86 as well, thanks.

**Comment by CastagnaIT** [comment] 2022-02-05 17:40
Fixed in new release

**Comment by ZarzueloM** [comment] 2022-02-05 18:08
> I fix it after read discussions (on osmc/rasp3)
> 
> /home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
> 
> ```
> 
> --- msl_handler.py.orig    2022-02-02 10:45:03.567218417 +0100
> +++ msl_handler.py    2022-02-02 12:15:37.920057323 +0100
> @@ -182,7 +182,7 @@
> 
>          params = {
>              'type': 'standard',
> -            'viewableId': [viewable_id],
> +            'viewableId': viewable_id,
>              'profiles': profiles,
>              'flavor': 'PRE_FETCH',
>              'drmType': 'widevine',
> ```

It worked on a RaspberryPI 2 + LibreElec + Kodi 18 Leia
Just the path is different: /storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py
Thanks!!

**Closed** 2022-02-05 18:24 UTC
Labels: Resolution: Fixed
