### ISSUE TITLE
Wrong audio language

### ISSUE THREAD

**Issue by mivalsten** [CastagnaIT/plugin.video.netflix#639] opened 2020-05-14 17:31 UTC
#### Your Environment
- Netflix add-on version: 1.2.2
- Operating system version/name: Ubuntu Server 20.04 LTS
- Device model:  AtomicPI (x86 Intel Atom Z8350 SBC)

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Whenever new video is started, kodi plays it in German. Sometimes other languages, but mostly german. I set it to polish manually and select "remember this settings".

#### Expected behavior

Audio should be in polish.

#### Actual behavior

Audo is not in polish.

#### Steps to reproduce the behavior

1. Play video
2. Get wrong audio.
3.

### Debug log

The debug log can be found from this link: https://gist.github.com/mivalsten/764f7e2785d6f980185405aa5fe2516e

#### Installation
* [x] I'm using other Netflix Repo from this repository.
* [ ] I'm using a different source

**Comment by notoco** [comment] 2020-05-14 18:42
Na szybko - w kodi (nie we wtyczce Netflix) ustawiłeś język audio na polski?

**Comment by grzegorzkawkaosik** [comment] 2020-05-14 19:01
Nie, tam mam angielski którego używam na co dzień, ale syn niestety jeszcze nie mówi, więc bajki muszą lecieć po polsku.
=====
Question above asks if I had set Language in Kodi Regional settings to Polish which I did not and am using English there.

**Comment by notoco** [comment] 2020-05-14 19:57
The plugin sets the language to the one set in kodi. If you have English set, the default audio will be English. The setting you mentioned applies only to a specific series or movie - it is not transferred to other series.
The solution that comes to my mind is switching audio using the keyboard shortcut ex:
<k>AudioNextLanguage</k>

**Comment by grzegorzkawkaosik** [comment] 2020-05-14 20:01
Well, that would be even better, as I hate polish translations with a heated passion, I spent my whole childhood learning English so I wouldn't need to listen to Mr Knapik and Boberek. :)
Unfortunately, I suspect it plays first audio track on the list, which for me is almost always German, which I did not learn properly in school. :(

There is some kind of error, check around line 1550 in provided log. I don't know python so I have trouble debugging it myself.

**Comment by notoco** [comment] 2020-05-14 20:09
In input stream adaptive you have not set the stream selection to manual? It should be set to auto

**Comment by grzegorzkawkaosik** [comment] 2020-05-14 21:46
Yes, it is on auto.

**Comment by CastagnaIT** [comment] 2020-05-15 06:54
@mivalsten you have to provide a debug log as instruction in Readme, your log is without nf debug
and i need more info to reproduce the problem, get me this info:
- Kodi settings -> Player -> Language - What is the audio language preferred?
- Kodi settings -> Interface -> Regional -> Language - What language you have set?

As notoco says, verify  input stream adaptive on settings `stream selection` _must **not** be set_ as `Manual`

>There is some kind of error, check around line 1550 in provided log. I don't know python so I have trouble debugging it myself.

Yes i have to analyze the "KeyError" error

Anyway here the main problem is Kodi 18.x not the add-on,
in the wiki is explained: [When you resume a previous playback it do not keep the language of your choice](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#When-you-resume-a-previous-playback-it-do-not-keep-the-language-of-your-choice)
maybe i should put a more suitable title for this definition

**Comment by mivalsten** [comment] 2020-05-15 07:11
Hi @CastagnaIT, thank you for your work. :)

Preferred Player audio: Polish
Interface Regional Language: English

Proper log: https://gist.github.com/mivalsten/d6cebc7b1d1245795e8ae768fdac6e4b
Audio error is at 2600

**Comment by CastagnaIT** [comment] 2020-05-15 08:30
I can not reproduce the KeyError issue to my pc station

seem that your kodi save wrong info:
`{u'index': 0, u'name': u'AAC ', u'language': u'unk', u'channels': 2, u'codec': u'aac', u'bitrate': 130858}`

language 'unk' means language unknown, weird...
then after this try to restore also the subtitle but fails with KeyError i think due to wrong data

in the audio language list window, does the list of languages have correct names on all available languages?

Try install this and provide new log, this is not a fix only for debug info
[plugin.video.netflix_1.2.2_20200515_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4633143/plugin.video.netflix_1.2.2_20200515_t1.zip)

**Comment by mivalsten** [comment] 2020-05-15 09:45
New log: https://gist.github.com/mivalsten/6989f561a75f782a0d90e1fe9189ed3a

**Comment by CastagnaIT** [comment] 2020-05-15 11:29
Ok now "unk" case is managed and KeyError should no longer appear
try this:
[plugin.video.netflix_1.2.2_20200515_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4634035/plugin.video.netflix_1.2.2_20200515_t2.zip)

then do this:
-play a episode
-open audio language window list choose a different audio language (not polish) press ok and _wait 3 seconds_
-now again change audio language and set Polish press ok and _wait 3 seconds_
-try another episode and let me know

**Comment by mivalsten** [comment] 2020-05-15 11:38
Hi, it worked! Thanks!

In case you want to check some things, here is newest log: https://gist.github.com/mivalsten/d8554077deeb68bf84a64e0568459047

**Closed** 2020-05-17 13:26 UTC
Labels: Resolution: Fixed
