### ISSUE TITLE
The Chinese subtitles tracks are not selected automatically

### ISSUE THREAD

**Issue by MAN-GOR** [CastagnaIT/plugin.video.netflix#1348] opened 2022-05-25 05:03 UTC
### Netflix add-on version

1.18.6

### Operative systems used

Android, Windows

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

1. I selected "Chinese (Traditional)" as preferred language for subtitles in the Kodi settings.
When I play a video in the Netflix addon the subtitles are turned off. I have to manually select "Chinese - Hant".

2. I selected "Chinese (Simple)" as preferred language for subtitles in the Kodi settings.
When I play a video in the Netflix addon the subtitles are turned off. I have to manually select "Chinese - Hans".

### Steps to reproduce the behavior

1. Change "Interface > Regional > Language" to "Chinese (Traditional)"
Select "Chinese (Traditional)" as preferred language for subtitles in the Kodi settings.
Play a video in the Netflix addon which has an "Chinese - Hant" subtitle track.

2. Change "Interface > Regional > Language" to "Chinese (Simple)"
Select "Chinese (Simple)" as preferred language for subtitles in the Kodi settings.
Play a video in the Netflix addon which has an "Chinese - Hans" subtitle track.

### Debug log - mandatory

https://paste.kodi.tv/dasicucana.kodi

### Screenshots

![螢幕擷取畫面 (3)](https://user-images.githubusercontent.com/92726453/170183410-4181a150-6fa4-4d12-aee1-363206b29b69.png)
![螢幕擷取畫面 (4)](https://user-images.githubusercontent.com/92726453/170183421-daa4ba31-5dc7-45b0-b175-c84fbb3382e3.png)

**Comment by CastagnaIT** [comment] 2022-05-29 09:59
this is a know problem since Kodi not support country codes
so kodi seem to support only zh-cn/zh-tw

one solution already adopted in another similar situation is replace
zh-Hant with zh-cn
zh-Hans with zh-tw

but i also know that exists more macrolanguages like zh-CN, zh-HK, ...
is possible that there is only hant/hans language in catalogue but i am not sure

can you check if you are able to find other type of chinese macrolanguage in catalogue?
maybe try check also some old chinese movie?

please check also on audio languages

**Comment by CastagnaIT** [comment] 2022-06-05 14:29
if no response in next days this will be closed and not fixed
since there is no collaboration

**Comment by MAN-GOR** [comment] 2022-06-06 05:13
Sorry for not replying before.
There are no errors in audio language.

There are only "Chinese - Hant" and "Chinese - Hans" in the catalog.

If it is a kodi problem and cannot be solved, at least select a random "Chinese" subtitle track and display the subtitles.
Now the subtitles will not be displayed and need to be turned on manually.

**Comment by CastagnaIT** [comment] 2022-06-06 06:15
is not what i asked in my previous comment,
i try reformulate my question:

can you check if you are able to find other types of chinese audio/subtitles languages other than Hant/Hans in video catalogue and specify the names?

**Comment by MAN-GOR** [comment] 2022-06-06 08:17
I only found "Chinese - Hant" and "Chinese - Hans" in the Chinese subtitle language of the video directory, no other types
just like this picture
![image](https://user-images.githubusercontent.com/92726453/170183421-daa4ba31-5dc7-45b0-b175-c84fbb3382e3.png)

The Chinese audio language in the video directory is only "Chinese - DD+ - 2 channels", and the current add-on can automatically select the Chinese audio track

**Comment by CastagnaIT** [comment] 2022-06-06 14:20
thanks, i tried do go deeper for your use case

your languages "Chinese (Traditional)" and "Chinese (Simple)" are language packages installed separately in kodi

so as first, i tried replace the language code of subtitles with the language code of packages (zh_CN, zh_TW) as mentioned before,
and i have discovered that Kodi has an additional bug, so is not able to detect and select the languages installed as package,
so replacing the language code from the addon does not work either...

moreover also Kodi python module `xbmc.convertLanguage` have the same bug, by returning an empty string instead of the language code of the language package

for the time being an appropriate solution is not possible
without create a very nasty hack to falsify the language codes that suspect also will works partially,
and having several language workarounds already i think will only cause more confusion

therefore a appropriate solution will take time because will need to be fixed as first in kodi core
I will try to open a bug issue in Kodi when i can

**Comment by CastagnaIT** [comment] 2022-07-07 06:20
this is another workaround that force kodi to select a language
the hours needed to implement a kind of thing on each addon
is better invest in to fix the problem in kodi itself...

**Comment by Liqianyu** [comment] 2022-07-08 20:49
@MAN-GOR 
matthuisman's solution does bypass Kodi to solve the problem, but it doesn't apply to other Add-ons
I think to fix it once and for all, we need to go to https://github.com/xbmc/xbmc/issues https://forum.kodi.tv/ suggest Kodi improvements.
I agree that the issue should be fixed in Kodi. And Kodi needs to be extended to classify Chinese.

There are different variants of Chinese for different countries and regions, e.g. Mainland China, Hong Kong, Macau, Taiwan, Malaysia, Singapore are all different.
The region codes are CN, HK, MO, TW, MY, SG.

I think the subtitle language can be expanded from the current Chinese, Chinese (Simplified), Chinese (Traditional) to Chinese - Simplified - CN, Chinese - Simplified - MY&SG, Chinese - Traditional - HK&MO, Chinese - Traditional - TW, for Cantonese I know less, I think a single Chinese - Yue(or Cantonese) is enough.
The audio language should be expanded from the current Chinese, Chinese (Simplified), Chinese (Traditional) to Chinese - Mandarin - CN, Chinese - Mandarin - TW, Chinese - Mandarin - MY&SG, Chinese - Cantonese
"Simplified“、“Traditional”, which describes written language rather than audio.

Consider that in most cases, multiple variants will not be available at the same time. 
So I think according to the user-set audio and subtitle language, the priority is to match the regional variants, followed by the same glyphs. If not found in matching other glyphs that may exist (e.g. Simplified does not exist, match Traditional), the same for Mandarin.

See https://en.wikipedia.org/wiki/Sinitic_languages

**Comment by CastagnaIT** [comment] 2022-07-11 07:50
@Liqianyu yeah i have already opened an Issue https://github.com/xbmc/xbmc/issues/21533
more or less i have understand what changes are needed in kodi core
when i will have time for this i will try to implement a way to get language code of installed language packages in the missing parts of kodi

for glyphs of fonts is a whole other thing, for subtitles this should works already just add the appropriate fonts in kodi fonts folder, at least this works for Kodi 20, for GUI font purpose the thing is different, and require a massive change in Kodi, someone has already proposed a change but incomplete, more likely will be done in the future Kodi 21

**Comment by CastagnaIT** [comment] 2022-08-23 15:48
hi @MAN-GOR sorry for the delay but i had a lot of other works to do

i have fixed kodi ([PR 21776](https://github.com/xbmc/xbmc/pull/21776)) so now should works as expected
these are the test builds, choose the preferred:
Windows64: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220823-df3a4336-language_fix-x64.exe
Android ARM: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20220823-df3a4336-language_fix-26346-armeabi-v7a.apk
Android ARM64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220823-df3a4336-language_fix-23855-arm64-v8a.apk

I would appreciate feedback from some of you

**Comment by MAN-GOR** [comment] 2022-08-23 21:46
thank you very much @CastagnaIT 
But am I missing something?

I uninstalled "KODI 19"
Then install the "KODI 20 Windows 64 exe" provided by you
"Chinese (Simplified)" and "Chinese (Traditional)" language packs installed
![螢幕擷取畫面 2022-08-24 053633](https://user-images.githubusercontent.com/92726453/186271786-4e4a2dd7-9b39-41bf-9ca6-563e61a1aa87.png)
and define the language code in "advancedsettings.xml"
My "Preferred Subtitle Language" select "Chinese (Traditional)" or "MyCustomDesc(zh-tw)"
![螢幕擷取畫面 2022-08-24 052351](https://user-images.githubusercontent.com/92726453/186271834-d4d1fb70-5c79-4d34-bbb5-3089db4a53be.png)
But I tested a lot of possibilities and it didn't work either
![螢幕擷取畫面 2022-08-24 053342](https://user-images.githubusercontent.com/92726453/186271879-3fd98546-d651-4a46-872a-057cd5c0be46.png)
![螢幕擷取畫面 2022-08-24 053511](https://user-images.githubusercontent.com/92726453/186271922-56ad8855-86ed-41ac-92b5-f8dd83e002cb.png)
![螢幕擷取畫面 2022-08-24 053536](https://user-images.githubusercontent.com/92726453/186271940-a4da7732-1f2d-4b09-9f3e-59fe55cab7a8.png)
![螢幕擷取畫面 2022-08-24 053809](https://user-images.githubusercontent.com/92726453/186271959-f1389e5f-e840-4490-8330-1ae3b3dd258c.png)

**Comment by CastagnaIT** [comment] 2022-08-24 06:24
i will try check
i have tested only web streams, so not file

**Comment by MAN-GOR** [comment] 2022-08-24 10:46
> i will try check i have tested only web streams, so not file
> 
> however from the screenshot your file looks weird seems there are too many language code duplicates with same properties

Because this is what I created to test which subtitle will be selected successfully.

On the version you gave me, my "Add-ons" cannot display zip files, but in the "File manager" it can show...
So I can't install "Add-ons" to test streaming.

But my first test was to upgrade from "kodi19" to "kodi20", and my kodi19 has installed streaming "add-ons". Unfortunately, it doesn't work on streaming either.
At the time I thought it was because of a bug in upgrading from "kodi19" to "kodi20", so I uninstalled and reinstalled.

**Comment by CastagnaIT** [comment] 2022-08-24 12:54
you have right there is a bug in kodi that not allow show the .zip files

on what concern the problem with video files
unfurnately the problem is in ffmpeg library that kodi uses, and this cannot be fixed by our part
but, i have add a possible workaround, to allow kodi recognize the right language code,

the workaround consists in to add the language code on the track "title", as following example: `(zh-tw)`
so please try edit your file remove the duplicates and put also in the "title" the language code enclosed with brackets

This is the new build with all fixes:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220824-6bf6426b-language_fix-x64.exe

**Comment by MAN-GOR** [comment] 2022-08-27 08:35
umm... Let me check again.
After installing the kodi 20 you provided, I need to switch "Language" to "Chinese (Traditional)" in "System>Interface>Regional" to install the language pack.
Then switch the "Preferred subtitle language" to "Chinese (Traditional)" in "System>Player>Language", Or create a new file "advancedsettings.xml" and switch "Preferred subtitle language" to "MyCustomDesc(zh-tw)".
Finally, the add-ons of "Netflix" should automatically select "Chinese (Traditional)" subtitles.

But I tested it and I couldn't successfully select "Chinese (Traditional)" automatically...
Should I enable debugg logging to provide log files?

**Comment by CastagnaIT** [comment] 2022-08-27 08:44
you pointed out a problem i had not seen, i will check,

since you have installed the language pack can you testing by removing lang values in advancedsettings.xml?

**Comment by MAN-GOR** [comment] 2022-08-27 08:55
Do you mean delete the "advancedsettings.xml" file and only switch the "Preferred subtitle language" to "Chinese (Traditional)" in "System>Player>Language"?
Or something else? Sorry I don't quite understand.

**Comment by CastagnaIT** [comment] 2022-08-27 09:07
to be sure remove advancedsettings.xml file,
then when you run kodi make sure that in the  "Preferred subtitle language"  is set "Chinese (Traditional)"

**Comment by MAN-GOR** [comment] 2022-08-27 09:22
I can confirm that the "advancedsettings.xml file" has been deleted.
I even uninstalled kodi20 and deleted all user data, then reinstalled.
Switch "Language" to "Chinese (Traditional)" in "System>Interface>Regional" to install the language pack.
Switch the "Preferred subtitle language" to "Chinese (Traditional)" in "System>Player>Language"
But it still fails to automatically select "Chinese (Traditional)"

**Comment by CastagnaIT** [comment] 2022-08-27 09:30
i am not able to reply your problem to me works as expected
please disable all following addon settings as shown below, and try again
![immagine](https://user-images.githubusercontent.com/3257156/187024234-a1b6c836-0822-4354-b89c-f4dcf7fc7285.png)
and also please give me the title of your movie, in hoping is not geo locked

**Comment by MAN-GOR** [comment] 2022-08-27 09:43
No luck for me.
The TV show I tested was "Chesapeake Shores" S06
![螢幕擷取畫面 (55)](https://user-images.githubusercontent.com/92726453/187024732-b42a92d0-9e9b-4e81-be5e-f51d15772ffe.png)
![螢幕擷取畫面 (58)](https://user-images.githubusercontent.com/92726453/187024771-1ee646a8-80d9-4114-8cae-9c1ee17d444c.png)
![螢幕擷取畫面 (56)](https://user-images.githubusercontent.com/92726453/187024738-0d6a7d7d-e925-4bee-8fcc-def95f46e9b5.png)
![螢幕擷取畫面 (57)](https://user-images.githubusercontent.com/92726453/187024742-32213f15-827f-48e0-b567-665706f2ed5b.png)

**Comment by CastagnaIT** [comment] 2022-08-27 09:57
ah ok now its clear this is right because in Kodi 
`Chinese (Traditional)` is the language code "zh-tw"
and
`Chinese (Simple)` is the language code "zh-cn"

but netflix stream use these subtag "Hans"/"Hant"
in this use case you have to add in the advancedsettings.xml this:

```
<advancedsettings>
<languagecodes>
  <code>
    <short>zh-Hant</short>
    <long>Chinese (Traditional)</long>
  </code>
  <code>
    <short>zh-Hans</short>
    <long>Chinese (Simple)</long>
  </code>
</languagecodes>
</advancedsettings>
```

**Comment by MAN-GOR** [comment] 2022-08-27 10:16
Thank you, It work now. The current "advancedsettings.xml" successfully automatically selects "Chinese (Traditional)"
But I still don't know how to automatically select "Chinese (Traditional)" subtitles for local files, whether it is the previous "zh-tw" or the current "zh-Hant"

**Comment by CastagnaIT** [comment] 2022-08-27 10:45
For local files you have the needed to edit the file itself, for example with MKVToolNix software

![immagine](https://user-images.githubusercontent.com/3257156/187026721-0c217b10-1813-46db-88cb-3e6c605e7c2e.png)

**Comment by CastagnaIT** [comment] 2022-08-27 10:52
sorry sorry my browser went crazy and closed the thread and the message that i was writing, now reopened

**Comment by MAN-GOR** [comment] 2022-08-27 10:54
it's ok. I got it now.
I thought the parentheses weren't needed before...

**Comment by CastagnaIT** [comment] 2022-08-27 10:57
yes as the screenshot example

**Comment by CastagnaIT** [comment] 2022-08-28 12:38
just to inform you that in my final changes in Kodi i made easier things for local files,
so will be optional add the round brackets
so if you prefeer you can add the language code in the track "title"/"name" also without brackets

**Comment by MAN-GOR** [comment] 2022-08-29 01:12
Thanks for all you do, but could you please add "Chinese (Yue)" to "Preferred subtitle and audio language"?
The language code used for "audio" is "yue", the language code used for "subtitles" is "yue" or "zh-HK".

Add "Chinese (Yue)" to "advancedsettings.xml":
![螢幕擷取畫面 2022-08-29 090944](https://user-images.githubusercontent.com/92726453/187104019-e4bfca00-f258-412e-928c-4abe03affccd.png)
audio test, Use "The Boss Baby: Back in Business" in "Netflix".
Before, will be displayed as "Unknown".
![螢幕擷取畫面 (59)](https://user-images.githubusercontent.com/92726453/187104042-08f0844d-467c-4bc4-8f17-a556a8e6ade1.png)
after, will be displayed as "Chinese (Yue)".
![螢幕擷取畫面 (60)](https://user-images.githubusercontent.com/92726453/187104051-1694b350-81b3-4b98-9070-3a3482605c8d.png)

subtitle test, Since "Netflix" does not have "Hong Kong/Cantonese" subtitles, so use "Toy Story 4" in "Disney+".
Before, will be displayed as "Unknown".
![螢幕擷取畫面 (61)](https://user-images.githubusercontent.com/92726453/187104071-13e1f827-3305-470a-aca1-6f80eb468d8a.png)
after, will be displayed as "Chinese (Yue)".
![螢幕擷取畫面 (62)](https://user-images.githubusercontent.com/92726453/187104080-de755a9c-6923-40be-a5a0-8e6dfa419d8c.png)

**Comment by CastagnaIT** [comment] 2022-08-29 07:03
this addon do not works with external local subtitles files,
then you have to download/open external subtitles with the kodi GUI
or try find an add-on that auto-download the subtitles when playback starts

**Comment by MAN-GOR** [comment] 2022-08-30 04:52
I am sorry. I mean if I don't create "advancedsettings.xml", KODI will not be able to automatically select "Cantonese audio track" on "Netflix".
You can test "The Boss Baby: Back in Business" from "Netflix".
Before "advancedsettings.xml" is created, "Cantonese audio track" will be displayed as "Unknown", Only after creating "advancedsettings.xml" will the name be displayed correctly and automatically selected.

**Comment by CastagnaIT** [comment] 2022-08-31 07:16
`yue` its ISO 639-3 and can be used in IETF BCP47 as is without use it as subtag (`zh-yue`)
but Kodi support ISO 639-1 so `yue` will be unknown
yes the correct way is that you add it to advancedsettings

**Comment by CastagnaIT** [comment] 2022-09-02 11:46
language selection is managed by Kodi core not by addons, but, an addon could implement some workaround that override kodi language selection,
i cannot speak of Disney addon i have no idea how it works

> unless I set the subtitle language to Chinese, but then Netflix will not automatically turn on and select subtitles.

in netflix addon you can try enable setting "prefer audio/subtitle language with country code" on "playback" setting category
and try to see if solve the situation

otherwise, if not works,
you can try experiment this solution, set same "Chinese" language name to the two variants as follow:
```
<languagecodes>
    <code>
        <short>zh-Hans</short>
        <long>Chinese</long>
    </code>
    <code>
        <short>zh-Hant</short>
        <long>Chinese</long>
    </code>
    <code>
        <short>TW</short>
        <long>Cmn</long>
    </code>
    <code>
        <short>cmn</short>
        <long>Chinese</long>
    </code>
    <code>
        <short>yue</short>
        <long>Chinese - Yue</long>
    </code>
</languagecodes>
```

**Comment by CastagnaIT** [comment] 2022-09-03 16:32
i close the issue since fixes has been merged for the next Kodi 20 Nexus release

**Closed by CastagnaIT** 2022-09-03 16:32 UTC
Labels: Bug, Triage: Confirmed, Resolution: External - Fixed
