### ISSUE TITLE
Unable to Login Using Authentication Key

### ISSUE THREAD

**Issue by 1Map** [CastagnaIT/plugin.video.netflix#1182] opened 2021-06-04 22:53 UTC
I have latest Raspberry Pi 4, Latest Kodi and followed your Wiki page step-by-step to install with NF Authentication Key and Pin.  Problem is that, although I type my Pin in correctly, it keeps saying "Invalid Pin".  Really stuck here.

**Comment by jakermx** [comment] 2021-06-05 15:47
make sure you are running https://www.dropbox.com/sh/ls3veptflvneub1/AADUXio4xjOcTndivDvBY8_Xa/NFAuthenticationKey_Linux_1.1.4.zip?dl=0

and....please check you have the same time zones and both devices are NTP Sync.

it could make an invalid PIN for another system due bad date and time.

Keep us posted

**Comment by 1Map** [comment] 2021-06-06 08:44
Couple of issues here.  I use windows, not linux and already tried as follow:

Installed repository from (Note I am using latest Kodi 19.1 with LibreElec 10 - Beta on my Raspberry Pi 4)
https://github.com/castagnait/repository.castagnait/raw/matrix/repository.castagnait-1.0.0.zip

I then used the following to generate the NF Authentication Key:
https://www.dropbox.com/sh/80zv4umiiyx8ok1/AAABi-vk9CKNNXvpmzkCRTiIa?dl=0

Then copied the key to my Pi and open Netflix and Authenticated with this key.  Entered the correct Pin, but it says **Invalid Pin**

**Comment by CastagnaIT** [comment] 2021-06-06 09:16
i do not find errors on addon or in the NFAuthenticationKey for Windows
then the problem look like in your side
maybe you are using a wrong keyboard layout that cause you to write wrong chars
or simply you are still typing the wrong pin number

**Comment by ThoGru80** [comment] 2021-06-17 05:34
Can't confirm the error! I also use the Windows version to create the key! Then I can log in as normal with the PIN and password!

**Comment by CastagnaIT** [comment] 2021-06-17 09:36
If no reply from author this issue will be closed in next days

**Comment by 1Map** [comment] 2021-06-17 11:38
Yes, the problem was that you need to run the NFAuthenticationKey for Windows with elevated permission (As Administrator).  That did the trick.  I can now login on my Pi, but now the videos does not play.

**Comment by ThoGru80** [comment] 2021-06-17 11:44
I think is a widewine Probleme ... 

watching at LibreElec 

My T95Mini run with the old widewine and my Shuttle (x86) with the new one and all Movie from Netflix run without problems (other addons she used widewine run without any problems too)

**Comment by CastagnaIT** [comment] 2021-06-17 11:44
NFAuthenticationKey works without administrator access,
this means that your current windows user account has some limits set

**Comment by CastagnaIT** [comment] 2021-06-17 11:51
for all ARM devices like RPI with LibreELEC OS there is problems with Widevine
that at this time are in testing

you have to make your LibreELEC Widevine compatible by following this:
https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/

but in last weeks other things are changed and i do not know if the linked page above is updated

**Comment by 1Map** [comment] 2021-06-17 11:59
I am running LibreElec - Latest version on my Raspberry Pi 4

The message I am getting is:

![image](https://user-images.githubusercontent.com/1152458/122392356-17f4b080-cf74-11eb-8b98-7fbc86cdf8f6.png)

**Comment by ThoGru80** [comment] 2021-06-17 12:06
This is working for me ....
Select the "InputStream Helper" add-on (at user add-ons -> program add-ons).

Select "Configure".

Downgrade to the former (working) Widevine version.
https://forum.libreelec.tv/thread/24076-le-9-2-and-le10-fix-for-widevine/?postID=156866#post156866

**Comment by CastagnaIT** [comment] 2021-06-17 12:22
I received a reply from LE developers,
current blog instructions are updated: https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/
for the current released LE images so:
LE 9.2.7
LE 10 (9.95.4)

but soon will be released new LE images with more stable Widevine support,
which (in theory) should already be enabled by default

in any case if new images are installed is not needed downgrade the Widevine version

**Comment by CastagnaIT** [comment] 2021-06-23 15:53
closed due to inactivity

**Closed by CastagnaIT** 2021-06-23 15:53 UTC

**Comment by hwoehrle** [comment] 2021-12-27 20:22
> Yes, the problem was that you need to run the NFAuthenticationKey for Windows with elevated permission (As Administrator). That did the trick. I can now login on my Pi, but now the videos does not play.

I can confirm this. Same issue for me.  NFAuthenticationKey is created on WIndows (an normal user) without error. On Kodi i get an Error "Woring PIN". When generating the file as admin, all works fine.

**Comment by FlowersPowerz** [comment] 2024-02-19 13:58
I have the same problem, invalid pin also if I generate the auth with admin privileges
