### ISSUE TITLE
TypeError: 'hdrtype' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by Sparh4wk** [CastagnaIT/plugin.video.netflix#1512] opened 2022-12-09 04:44 UTC
### Netflix add-on version

1.20.2+matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

After selecting profile I cant open anything else.

### Steps to reproduce the behavior

1. Open addon
2. Select profile
3. Select My list or anything else

### Debug log - mandatory

https://paste.kodi.tv/gajuceteyo.kodi

**Comment by CastagnaIT** [comment] 2022-12-09 10:50
this is due to last Kodi 20 nightly versions which made a change to the Python API and broken the addon
already fixed but not released yet

if you dont want wait the new add-on release
rollback Kodi to previous old version until new add-on version will be released

**Comment by kokikoku** [comment] 2022-12-12 12:41
Same error occured  after update Kodi V20 RC1. Waiting for add-on new release.

**Comment by CastagnaIT** [comment] 2022-12-18 09:09
new release published

**Closed by CastagnaIT** 2022-12-18 09:09 UTC
Labels: Bug, Triage: Confirmed, Resolution: Fixed

**Comment by Gujal00** [comment] 2023-01-17 08:06
@CastagnaIT 
The problem is continuing on 1.18.8+matrix1 running on CoreElec 20.0-Nexus_nightly_20230117. Any suggestions, please?
