### ISSUE TITLE
When subtitles are displayed for on-screen text subtitles for dialog are not displayed.

### ISSUE THREAD

**Issue by mlidbom** [CastagnaIT/plugin.video.netflix#1153] opened 2021-05-06 06:09 UTC
#### Your Environment
- Netflix add-on version: 1.12.4 
EDIT: I've upgraded to Kodi 19 and version 1.15.1+matrix.1 of the Netflix plugin. The bug remains.
- Operating system version/name: Windows 10

Used Operating system:
* [ x] Windows

### Describe the bug

When subtitles are displayed for on-screen text subtitles for dialog are not displayed.

#### Expected behavior

Dialog subtitles should be displayed together with on-screen text subtitles.

#### Actual behavior

Only on-screen text subtitles are displayed and no subtitles are displayed for dialog.

#### Steps to reproduce the behavior

1. Play this video with english subtitles. https://www.netflix.com/watch/70303634?trackId=200257859
2. Fast forward to approximately 15:55
3. Watch the following 20 seconds or so

### Debug log

The debug log can be found here:

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6432128/kodi.log)

#### Screenshots

Correct subtitles as displayed on netflix website.
![subtitles-netflix](https://user-images.githubusercontent.com/143203/117249658-3f6b4000-ae42-11eb-8527-30319307d023.png)

Incorrect subtitles as displayed with plugin
![subtitles-kodi](https://user-images.githubusercontent.com/143203/117248791-d636fd00-ae40-11eb-8efc-40ffdec1d3f1.png)

**Comment by CastagnaIT** [comment] 2021-05-06 08:52
This have to be fixed on Kodi, i have tried to open a Kodi Issue https://github.com/xbmc/xbmc/issues/19698

**Comment by CastagnaIT** [comment] 2021-05-06 10:49
@mlidbom are you running Kodi in fullscreen or windowed?

**Comment by CastagnaIT** [comment] 2021-05-06 10:51
in fullscreen i do not see subtitle problems
and please test with original Kodi skin, not custom skin

**Comment by Essam311** [comment] 2021-05-06 11:00
@mlidbom As a temp solution you could use the modified Netflix plugin from @Paco8 repo on Kodi Matrix, it displays the subtitles in ssa format, in Improved subtitles settings disable "Allow timestamp manipulation" 

https://github.com/Paco8/kodi-repo/blob/master/packages-kodi-19/repository.paco8/repository.paco8-1.1.0.zip

This is how it looks in the modified Netflix plugin by @Paco8.

![ass](https://user-images.githubusercontent.com/59211054/117287260-748b8880-ae6a-11eb-95b1-5ae5ae35f6e2.png)



![222](https://user-images.githubusercontent.com/59211054/117286684-c5e74800-ae69-11eb-84a8-06992ede15d4.png)

**Comment by Essam311** [comment] 2021-05-06 11:16
@CastagnaIT Kodi seems to be not supporting the alignment tags in the webvtt subtitles, it looks like this

 
![webvtt](https://user-images.githubusercontent.com/59211054/117288926-5030ab80-ae6c-11eb-876c-e522ce8159e4.png)

when it should look like this.

![ass](https://user-images.githubusercontent.com/59211054/117288978-62aae500-ae6c-11eb-831b-b2a68f26812d.png)

261
00:14:58.900 --> 00:15:06.365  position:50.00%,middle  align:middle size:80.00%  line:10.00% 
FILE OF TRUE CROSS ACADEMY
REGIONAL EARTHQUAKE DAMAGE REPORTS

262
00:14:59.275 --> 00:15:02.570  position:50.00%,middle  align:middle size:80.00%  line:79.33% 
That said, I'm going to continue
to keep an eye on Rin Okumura.

![tags](https://user-images.githubusercontent.com/59211054/117289595-0eeccb80-ae6d-11eb-8d5d-8b44a9c56420.png)

**Comment by mlidbom** [comment] 2021-05-06 18:45
@CastagnaIT 

Thanks you very much for taking action on this super quick. It is very much appreciated!

>This have to be fixed on Kodi, i have tried to open a Kodi Issue xbmc/xbmc#19698
Hmm. Unlike what you describe there, I see no subtitles displayed at all, see screenshots. I've been using Kodi for many years with countless videos like this and never have I encountered this issue before. 

Strange that we see different behavior. I wonder what is different between our environments. Hmm, I run dual screens with 4K resolution. I wonder if either resolution or dual screen is relevant. I will run some tests and report back the results. I'll also test with and without hardware acceleration allowed.

> @mlidbom are you running Kodi in fullscreen or windowed?
I'm running fullscreen. 

>please test with original Kodi skin, not custom skin
I tried this and the result is exactly the same.

>@mlidbom As a temp solution you could use the modified Netflix plugin from @Paco8 repo on Kodi Matrix, it displays the subtitles in ssa format, in Improved subtitles settings disable "Allow timestamp manipulation"

Thank you! After experimenting some with resolutions I will switch to that version for an instant fix!

**Comment by mlidbom** [comment] 2021-05-06 19:03
@CastagnaIT 

It is resolution dependent. I tried with 1920x1080 and then I see the subtitles displayed as in your screenshots in the other issue that you opened. Hardware acceleration does not seem to have any impact. Single or dual screen did not seem to have any impact.

I'm guessing that the incorrect positioning does not properly scale with screen resolution and end up displaying the dialog off-screen when running in 4k resolution. I'll add this information to the issue that you opened.

**Comment by mlidbom** [comment] 2021-05-06 19:49
@CastagnaIT 
>@mlidbom As a temp solution you could use the modified Netflix plugin from @Paco8 repo on Kodi Matrix, it displays the subtitles in ssa format, in Improved subtitles settings disable "Allow timestamp manipulation"
>
>https://github.com/Paco8/kodi-repo/blob/master/packages-kodi-19/repository.paco8/repository.paco8-1.1.0.zip

This works perfectly. Now I can go back to watching in peace :)
Again. A great big thank you for the excellent and very fast response! 🥇

**Comment by Essam311** [comment] 2021-05-06 20:01
@mlidbom If you just want to see all the subtitles, in @CastagnaIT Netflix plugin just turn on "Disable WebVTT subtitle support" in the settings, you will get the same result like this screenshot, but you will not be able to get the subtitles for many languages like the Japanese, Chinese, Korean, Arabic and many others (I prefer using @Paco modified version from the Netflix plugin because using the subtitles in ass format fixes some problems with the subtitles in the Arabic language need to be fixed in Kodi, and I can change the border style of the subtitles).

![117288926-5030ab80-ae6c-11eb-876c-e522ce8159e4](https://user-images.githubusercontent.com/59211054/117356029-99581e00-aeb3-11eb-8735-5fa635091b78.png)

![25](https://user-images.githubusercontent.com/59211054/117356505-17b4c000-aeb4-11eb-8711-8b9e2ec97ce4.png)

**Comment by Essam311** [comment] 2021-05-06 22:27
@mlidbom Try using this subtitle file as external subtitle and see if the problem is still exist.

[Blue.Exorcist.S01E13.en.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6437926/Blue.Exorcist.S01E13.en.zip)

**Comment by Essam311** [comment] 2021-05-07 01:22
@mlidbom Is the dialog disappear in 4K throughout the episode?

**Comment by mlidbom** [comment] 2021-05-07 01:30
@Essam311 
Only while translations of on-screen text are displayed. Works fine with the paco8 workaround that you suggested though, so I'm all good. Thanks again for that tip :)

**Comment by CastagnaIT** [comment] 2021-08-11 16:43
with regard to incorrect off-screen text positioning
i'm working to make changes in to Kodi core to solve the problem at its root
that will see the light of day with Kodi 20 only

with regard to the dynamically text positioning in the top of screen, like the first screenshot
a different change is needed, maybe i will do in future

i close this Issue because now there is a WIP in Kodi

**Closed by CastagnaIT** 2021-08-11 16:43 UTC
Labels: Resolution: Waiting Kodi fixes, Resolution: External
