### ISSUE TITLE
Users may find unsupported Netflix projects

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#407] opened 2019-12-31 02:19 UTC
## Feature request
I'm submitting a proposal to improve users finding this Netflix project.

### Describe your request
Ensure users are installing the correct Netflix add-on in Kodi.

#### Describe the use case
In discussions with Kodi users many have tried the Netflix add-on and were not satisfied and in almost all cases they found the older @asciidisco or @caphm projects, or another outdated version.

I think it would be better if:
- This project would no longer state "forked from [caphm/plugin.video.netflix](https://github.com/caphm/plugin.video.netflix)".
  - see: [Delete fork dependency of a GitHub repository](https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository)
- Google/Bing/... would show correct hits
  - search for "Kodi Netflix" and report to each and every hit going to the older projects to modify the link to your project
- The documentation highlights adding the Netflix repository
  - so that at least people are not installing a specific version, but also get updates automatically

#### Describe an alternative
Moving it into the official Kodi repository.

**Comment by CastagnaIT** [comment] 2019-12-31 13:24
Clearer than that...
but i do not remove the fork

I will plan the addition to the Kodi repo
I have already spoken with some kodi devs in slack they agreed to leave the project to me

**Comment by dagwieers** [comment] 2019-12-31 13:54
For a lot of people the "forked from" means that this is not the upstream project, but a contributor's remote copy.

**Comment by CastagnaIT** [comment] 2019-12-31 14:02
and this is right😂it's just an evolution
i can not associate this as an original project, it is not true

**Comment by asciidisco** [comment] 2019-12-31 14:07
Thank you for taking over the project, I know it’s a bunch of work (which I’m not able to take in anymore).

Let me know what I can do to support the cause. Also, I’m gonna link to your repo from my Readme & let people know to use your fork.

Back in the day, the Kodi folks did not want to add it to the official repo, would be great if that changed.

**Comment by dagwieers** [comment] 2019-12-31 14:15
@CastagnaIT Removing the "forked from" does not mean it is an original project. IMO it is better for the project to acknowledge that most people are misled to think upstream is elsewhere and installing an old broken version instead.

**Comment by CastagnaIT** [comment] 2019-12-31 14:53
Hi asciidisco! I'm glad to hear from you
yes this project is getting huge and very complex, it is become very difficult to keep it stable for all platforms

especially for linux (many distributions/android versions/dedicated so) and there are too many devices, in the case of android some android 7 do not work well or also some chinese box android do not work well... user complaining often... LoOoL

I'm starting develop a way to communicate the progress of video viewing (so watched status)
thanks to https://github.com/nohajc/netflix-mitm-proxy i can look between original netflix req/resp data, the PR it is in embrional state at moment.

I don't know how much time you have to support this, but even simple help to reply to issues is accepted, and yes there are some things i do not know how solve

At the moment one ugly cat is that sometime when manifests are requested, there is a lack of languages in the audio streamings, this happen not to all videos but only for some
(mainly I'll just compare netflix website audio language and the same to kodi addon audio list)
i don't know how to solve (ref issue: "Limited Audio language list")

if it's all right with anyone, i will ask to github to remove the fork label

**Comment by CastagnaIT** [comment] 2020-01-16 18:06
Unfortunately, i have a bad news

this is the summary answer from one of the founders of Kodi organization

Netflix addon will never be included in the Kodi official repository
Despite this fork respects the use of the Netflix service in the most "legal" way available, this choice is to avoid a possible lawsuit by Netflix or one of the DRMs that support it with the Kodi organization. If in the future Netflix will welcome opensource collaborations in a better way, this choice will be re-evaluated, to now nothing can be done

I'm sorry, too, because it was all ready to go into the repository
We hope for a better future :)

**Comment by dagwieers** [comment] 2020-01-17 14:06
Since it will not be accepted to the Kodi repository, there is even more reason to ensure people end up in the right repository. I think we have to make a concerted effort to contact each of the pages that come up as hits on Google/Bing/... to ask them to change their references.

@asciidoc @caphm Could you maybe put your **plugin.video.netflix** repository in archive-mode? This makes it even more visible that the repository is no longer actively maintained. Both are often mentioned from other websites.

**Comment by CastagnaIT** [comment] 2020-01-18 12:44
caphm is already archived,
asciidisco might also archive his repository but liberty-developer use it for test purpose, so i don't know

I think that google is more focused on the original repo link also because a lot of old articles point to asciidisco github

I close the issue, what could be done was done

**Closed by CastagnaIT** 2020-01-18 12:44 UTC

**Comment by asciidisco** [comment] 2020-01-18 12:46
I'll leave the repo un-archived for liberty-dev, but adding a big disclaimer with a link to this repo in the readme is on my todo list. Just haven't found the time lately.

**Comment by CastagnaIT** [comment] 2020-01-18 12:51
no problem is not an urgent thing, because there is already a deprecated message...

**Comment by dagwieers** [comment] 2020-01-18 15:27
For the README you have to scroll down on a laptop. Maybe add it to the top title, or add a link to the top to the new repo as well?
